### PR TITLE
GH-2309: Close internally allocated InputStream

### LINKED ISSUE #2309: ResultSetFactory don't close the InputStream.
### Version

mian

### What happened?

ResultSetFactory don't close the InputStream. In the line of 69,function of load(String filenameOrURI, ResultsFormat format)

### Relevant output and stacktrace

_No response_

### Are you interested in making a pull request?

None

### PR DESCRIPTION
**Pull request by afs**
GitHub issue resolved #2309

----

 - [x] Commits have been squashed to remove intermediate development commit messages.
 - [x] Key commit messages start with the issue number (GH-xxxx, or if in JIRA, JENA-xxxx)

By submitting this pull request, I acknowledge that I am making a contribution to the Apache Software Foundation under the terms and conditions of the [Contributor's Agreement](https://www.apache.org/licenses/contributor-agreements.html).

### CODE REVIEW

**Review by kinow — APPROVED** [review]

File: jena-arq/src/main/java/org/apache/jena/query/ResultSetFactory.java [hunk 1]
```diff
@@ -65,12 +66,12 @@ public static ResultSet load(String filenameOrURI) {
...
      * @return ResultSet
      */
-
     public static ResultSet load(String filenameOrURI, ResultsFormat format) {
         if (format == null)
             format = ResultsFormat.guessSyntax(filenameOrURI);
-        InputStream in = IO.openFile(filenameOrURI) ;
-        return load(in, format) ;
+        try ( InputStream in = IO.openFile(filenameOrURI) ) {
+            return load(in, format) ;
```
Comment (rvesse) [inline jena-arq/src/main/java/org/apache/jena/query/ResultSetFactory.java:73]: I take it this doesn't prematurely close the `InputStream`, the runtime is smart enough to understand that there's still an active reference to the `InputStream` and not auto-close it in the happy path case?

**Review by rvesse — APPROVED** [review]

**Review by rvesse — APPROVED** [review]
Looks like a more robust approach

**Comment by afs** [comment]
> Looks like a more robust approach

Functional programming is the new indirection.
