### PR TITLE
GH-3473: Identify spatial objects by properties instead of types.

### LINKED ISSUE #3473: jena-geosparql: issues when building spatial index from assembler
### Version

5.5.0, 5.6.0-SNAPSHOT

### What happened?

What works: Loading an existing `spatial.index` file and rebuilding the spatial index using the Fuseki  Mod UI/API.

What fails: If the `spatial.index` file is absent, it should be created on Fuseki server start - via the assembler configuration - but there is weird behavior going on:

* According to https://www.mail-archive.com/users@jena.apache.org/msg21183.html the spatial index is created but not active on the dataset.
* ~~When trying to reproduce the issue on my setup, the spatial index setup created 64 spatial index files with name pattern `spatial.index-{0..63} ` with varying sizes until a final ordinary `spatial.index` file was created. Unclear whether no index or a random one eventually becomes the active one.~~ It turned out that this was an issue of my own docker setup and unrelated to Jena.

Saving a spatial index creates a temporary `spatial-index-{number}` file which only on success should overwrite the final `spatial.index` file - this is aimed to protect against (a) corrupted saves such as when shutting down a docker container while a write is active (b) concurrent recreation of the spatial index (should not really happen because only one indexing task can be active per dataset context).

~~So temporary spatial index files are not unexpected but it seems that there is a bugged loop on some level involved - could be a mix of endpoints, CPUs or (named) graphs.~~

### Relevant output and stacktrace

```shell

```

### Are you interested in making a pull request?

Yes

### PR DESCRIPTION
**Pull request by Aklakan**
GitHub issue resolved #3473 

Pull request Description: In `jena-geosparql`, replaced all lookups of spatial objects by type with lookups by the corresponding relevant properties. E.g. instead of searching for instances of type `geo:Geometry`, instances with `geo:asWKT`, `geo:asGML` and `geo:hasSerialization` properties are looked for.

* Consolidated all vocabulary-based graph access into `AccessGeoSPARQL` and `AccessWGS84` classes.
* Added benchmark. No performance issues revealed. Detailed results in this thread.
* Spatial Indexer UI: Replace mode with no selected graphs clears the index

* Added `computeIfAbsent/Present` methods to `Context`.
* Fixed missing override of `DatasetGraphRDFS.find()`
* Fixed possible resource leaks by changing `forEachRemaining` to `forEach` which closes the iterator after use. Credits to @SimonBin for spotting this.

----

 - [x] `GenericPropertyFunction` tests are covered by existing test suite
 - [x] Added new test cases based on the reported issue.
 - (I tested the UI change manually, but did not add an automated test)
 - [x] Commits have been squashed to remove intermediate development commit messages.
 - [x] Key commit messages start with the issue number (GH-xxxx)

By submitting this pull request, I acknowledge that I am making a contribution to the Apache Software Foundation under the terms and conditions of the [Contributor's Agreement](https://www.apache.org/licenses/contributor-agreements.html).

----

See the [Apache Jena "Contributing" guide](https://github.com/apache/jena/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Aklakan** [comment]
Converted to draft because there are more instances in GenericPropertyFunction that rely on explicit types, such as:
https://github.com/apache/jena/blob/c2d1a89991e35ab04f7cbce171dea9e8e7cf20af/jena-geosparql/src/main/java/org/apache/jena/geosparql/geo/topological/GenericPropertyFunction.java#L147-L151

I am looking into consolidating this into a separate set of methods that check whether resources are features or geometries and then retrieve the appropriate literal. Perhaps even an interface that let's one choose whether to classify resources by types or by properties.

File: jena-geosparql/src/main/java/org/apache/jena/geosparql/geo/topological/GenericPropertyFunction.java [hunk 1]
```diff
@@ -189,18 +183,7 @@ private QueryIterator findAll(Graph graph, Node boundNode, Node unboundNode, Bin
...
-            ExtendedIterator<Triple> featureTriples = graph.find(null, RDF.type.asNode(), Geo.FEATURE_NODE);
-            ExtendedIterator<Triple> geometryTriples = graph.find(null, RDF.type.asNode(), Geo.GEOMETRY_NODE);
-            spatialTriples = featureTriples.andThen(geometryTriples);
-        } else {
-            //Check for Geo Predicate Features in the Graph if no GeometryLiterals found.
-            spatialTriples = graph.find(null, SpatialExtension.GEO_LAT_NODE, null);
-        }
-        return spatialTriples;
+        return SpatialObjectAccess.findSpatialTriplesByProperties(graph, null);
     }
```
Comment (Aklakan) [inline jena-geosparql/src/main/java/org/apache/jena/geosparql/geo/topological/GenericPropertyFunction.java:204]: TLDR: Probably the lookup strategy should become a config option for the time being.

The code above is quite some opinionated/reasoning-centric logic - e.g. the presence of a single `foo a SpatialObject` triple would mean that all non-SpatialObject-resources of e.g. type `Geometry` would be ignored. Also, as reported in the issue, geometry resources with e.g. a WKT serialization but without the `Geometry` type are also ignored here.

My alternative implementation concats several iterators and adds filters that drop duplicates, but for fully materialized datasets this is performance-wise also far from ideal. Merge-scans of sorted iterators would help greatly here to efficiently iterate large amounts of resources that have co-occurrent properties, such as `geo:hasDefaultGeometry` and `geo:hasGeometry` - but we don't have them. AFAIK the TDB2 internals would be capable of this but not the general Graph API.
The `DatasetGraphRDFS` wrapper implementation doesn't solve this. In an ideal world, data access could go uniformly through an (virtual) RDFS reasoning layer - i.e. in the code above `?s a geo:SpatialObject` would be sufficient, and the details would be handled by other layers.

**Comment by Aklakan** [comment]
So benchmark results with this PR on a test dataset with 80K geometries are pretty much consistent with what was there before.

```
(p2_queryId)  (p3_inferences)  (p4_index)  (p5_jenaVersion)  Mode  Cnt  Score   Error  Units
          q1              off       false           current  avgt    5  2.460 ± 1.095   s/op
          q1              off       false             5.5.0  avgt    5  2.365 ± 0.259   s/op
          q1              off        true           current  avgt    5  0.250 ± 0.118   s/op
          q1              off        true             5.5.0  avgt    5  0.265 ± 0.035   s/op
          q1          virtual       false           current  avgt    5  2.947 ± 0.134   s/op
          q1          virtual       false             5.5.0  avgt    5  4.454 ± 0.820   s/op
          q1          virtual        true           current  avgt    5  0.310 ± 0.013   s/op
          q1          virtual        true             5.5.0  avgt    5  0.405 ± 0.012   s/op
          q1     materialized       false           current  avgt    5  2.168 ± 1.352   s/op
          q1     materialized       false             5.5.0  avgt    5  2.200 ± 1.186   s/op
          q1     materialized        true           current  avgt    5  0.149 ± 0.142   s/op
          q1     materialized        true             5.5.0  avgt    5  0.180 ± 0.129   s/op
          q2              off       false           current  avgt    5  0.079 ± 0.071   s/op
          q2              off       false             5.5.0  avgt    5  0.081 ± 0.012   s/op
          q2              off        true           current  avgt    5  0.070 ± 0.015   s/op
          q2              off        true             5.5.0  avgt    5  0.090 ± 0.007   s/op
          q2          virtual       false           current  avgt    5  0.158 ± 0.022   s/op
          q2          virtual       false             5.5.0  avgt    5  0.310 ± 0.021   s/op
          q2          virtual        true           current  avgt    5  0.159 ± 0.008   s/op
          q2          virtual        true             5.5.0  avgt    5  0.307 ± 0.010   s/op
          q2     materialized       false           current  avgt    5  0.047 ± 0.028   s/op
          q2     materialized       false             5.5.0  avgt    5  0.042 ± 0.007   s/op
          q2     materialized        true           current  avgt    5  0.069 ± 0.008   s/op
          q2     materialized        true             5.5.0  avgt    5  0.043 ± 0.004   s/op
```

A slight performance increase is seen on virtual inferences - most likely because because lookups by type (e.g. geo:Geometry) in addition would also have to scan all triples by which that type could be inferred. The new code just checks the properties directly.
```
          q1          virtual       false           current  avgt    5  2.947 ± 0.134   s/op
          q1          virtual       false             5.5.0  avgt    5  4.454 ± 0.820   s/op
```

The benchmark is compatible with jena-5.5.0 and thus adds type Geometry triples which with the now no core are longer needed. Plain geo:asWKT, geo:asGML or geo:hasSerialization is now sufficient.

**Comment by Aklakan** [comment]
The code itself ready for review. I will do a round of testing on our deployment for whether this reveals any issues and report back.

[Update] looked fine.

**Comment by Aklakan** [comment]
Hm, similar access patterns (e.g. the check for Geometry type triples) are used in SpatialIndexUtils, GenericSpatialPropertyFunction, SpatialObjectAccess. While at it, I'll consolidate this in one place.

**Comment by Aklakan** [comment]
The code is now consolidated.

File: jena-geosparql/src/main/java/org/apache/jena/geosparql/geo/topological/GenericPropertyFunction.java (hunk 1 above)
Comment (Aklakan) [reply jena-geosparql/src/main/java/org/apache/jena/geosparql/geo/topological/GenericPropertyFunction.java:204]: Configurable lookup strategies are overkill at this point. This pr already consolidates all graph access in one place so future enhancements in that area should be easy to add if needed.

File: jena-arq/src/main/java/org/apache/jena/rdfs/DatasetGraphRDFS.java [hunk 2]
```diff
@@ -67,6 +67,10 @@ public Graph getGraph(Node graphNode) {
         return new GraphRDFS(base, setup);
     }
 
+    @Override
```
Comment (afs) [inline jena-arq/src/main/java/org/apache/jena/rdfs/DatasetGraphRDFS.java:70]: As I read the code on main:

`find()` ->  
`find()` in DatasetGraphWrapper ->  
default method DatasetGraph.find() ->  
find(Node.ANY, Node.ANY, Node.ANY, Node.ANY);

so this is not necessary.

And `Node.ANY` is better than null :smile:

File: jena-arq/src/main/java/org/apache/jena/sparql/util/Context.java [hunk 3]
```diff
@@ -439,13 +434,36 @@ public static AtomicBoolean getCancelSignal(Context context) {
         }
     }
 
+    /** Atomic compute. */
```
Comment (afs) [inline jena-arq/src/main/java/org/apache/jena/sparql/util/Context.java:437]: Haven't I seen these Context changes in another of your PRs?

File: jena-arq/src/main/java/org/apache/jena/rdfs/DatasetGraphRDFS.java (hunk 2 above)
Comment (Aklakan) [reply jena-arq/src/main/java/org/apache/jena/rdfs/DatasetGraphRDFS.java:70]: The default find() method of DatasetGraphWrapper goes to the delegated dataset which does not have the inferences - so DatasetGraphRDFS does have to override it to use findInf. I'll add a test case.

https://github.com/apache/jena/blob/29e8a5601da695741a342059ab9810794f65f7ca/jena-arq/src/main/java/org/apache/jena/sparql/core/DatasetGraphWrapper.java#L195-L197

> `Node.ANY`

Agreed.

File: jena-arq/src/main/java/org/apache/jena/sparql/util/Context.java (hunk 3 above)
Comment (Aklakan) [reply jena-arq/src/main/java/org/apache/jena/sparql/util/Context.java:437]: It's part of the ExecTracker PR #3184 - but it also fits here where it is easier to review due to the size of the PR :)

File: jena-arq/src/main/java/org/apache/jena/rdfs/DatasetGraphRDFS.java (hunk 2 above)
Comment (Aklakan) [reply jena-arq/src/main/java/org/apache/jena/rdfs/DatasetGraphRDFS.java:70]: Added test case (fails without the fix) and switched to `Node.ANY`.

**Review by afs — APPROVED** [review]
