### PR TITLE
GH-1440: Fuseki/webapp. Command line argument processing.

### LINKED ISSUE #1440: Starting Fuseki Full with a dataset on the command line should default to read-only acess.
### Version

4.5.0

### What happened?

This is the original behaviour that seems to have got lost.

To start with an updateable, persistent dataset, `--update` is required.

### Relevant output and stacktrace

_No response_

### Are you interested in making a pull request?

Yes

### PR DESCRIPTION
**Pull request by afs**
GitHub issue resolved #1440.

Pull request Description:
* Fix for #1440 
   Read-only access when publishing a dataset.
* Convert creations template to new style endpoint descriptions. 
* Generalize template processing : existing templates still work.
* Review command line argument processing and organise logically.

----

 - [x] Tests are included.
 - [x] Commits have been squashed to remove intermediate development commit messages.
 - [x] Key commit messages start with the issue number (GH-xxxx or JENA-xxxx)

By submitting this pull request, I acknowledge that I am making a contribution to the Apache Software Foundation under the terms and conditions of the [Contributor's Agreement](https://www.apache.org/licenses/contributor-agreements.html).

### CODE REVIEW

File: jena-fuseki2/jena-fuseki-webapp/src/main/java/org/apache/jena/fuseki/cmd/FusekiCmd.java [hunk 1]
```diff
@@ -138,6 +131,11 @@ public FusekiCmdInner(String... argv) {
                 "Use an existing TDB database (or create if does not exist)");
             add(argMemTDB, "--memTDB",
                 "Create an in-memory, non-persistent dataset using TDB (testing only)");
+
+            // This is has proven confusing because it is like --conf.
```
Comment (kinow) [inline jena-fuseki2/jena-fuseki-webapp/src/main/java/org/apache/jena/fuseki/cmd/FusekiCmd.java:135]: s/This is has/This has/

**Review by kinow — APPROVED** [review]

File: jena-fuseki2/jena-fuseki-webapp/src/main/java/org/apache/jena/fuseki/cmd/FusekiCmd.java (hunk 1 above)
Comment (afs) [reply jena-fuseki2/jena-fuseki-webapp/src/main/java/org/apache/jena/fuseki/cmd/FusekiCmd.java]: Thank you!
