### PR TITLE
GH-3044: HashJoin iterator construction no longer eagerly builds hash probe table.

### LINKED ISSUE #3044: timeout parameter is not always respected by fuseki server
### Version

5.3.0

### What happened?

Using the Python _requests_ client, I am running sequentially a list of diverse SPARQL queries on a fuseki endpoint at localhost:3030, using POST request and a timeout parameter set to 10 s. For the few first lengthy query in the list, the timeout works as expected, i.e. the request terminates after approx 10 s and with a 503 status code. However at some point the timeout of subsequent queries is ignored, i.e.  the queries executing correctly and completely. 

As I suspect that this problem might be linked to the fuseki HTTP server, I have not investigated the content of the queries that are not timing out. Should I?

Thanks in advance,

  Marco

### Relevant output and stacktrace

```shell

```

### Are you interested in making a pull request?

None

### PR DESCRIPTION
**Pull request by Aklakan**
GitHub issue resolved #3044 
Pull request Description: Timeouts in QueryExecDataset were postponed until a so-far eager hash probe table construction completed because of locking. This PR proposes to initialize the hash probe table lazily such that the iterator construction becomes cheap and the lock is released quickly.

I added a test case that fails without the proposed fix.

----

 - [x] Tests are included.
 - (Documentation change and updates are provided for the [Apache Jena website](https://github.com/apache/jena-site/))
 - [x] Commits have been squashed to remove intermediate development commit messages.
 - [x] Key commit messages start with the issue number (GH-xxxx)

By submitting this pull request, I acknowledge that I am making a contribution to the Apache Software Foundation under the terms and conditions of the [Contributor's Agreement](https://www.apache.org/licenses/contributor-agreements.html).

----

See the [Apache Jena "Contributing" guide](https://github.com/apache/jena/blob/main/CONTRIBUTING.md).

### CODE REVIEW

File: jena-arq/src/main/java/org/apache/jena/sparql/exec/RowSetOps.java [hunk 1]
```diff
@@ -51,7 +51,7 @@ public static void consume(RowSet rowSet)
      * This operation consumes the RowSet.
      */
     public static long count(RowSet rowSet)
-    { return rowSet.rewindable().size(); }
+    { long c[] = {0}; rowSet.forEach(b -> ++c[0]); return c[0]; }
```
Comment (Aklakan) [inline jena-arq/src/main/java/org/apache/jena/sparql/exec/RowSetOps.java:54]: Intent: Avoid memory copy.

Comment (rvesse) [reply jena-arq/src/main/java/org/apache/jena/sparql/exec/RowSetOps.java:54]: Or maybe `rowSet.stream().count()` would be cleaner and still avoid the memory copy (though it has conversion to `Stream` overhead?

Comment (Aklakan) [reply jena-arq/src/main/java/org/apache/jena/sparql/exec/RowSetOps.java:54]: good point!

File: jena-tdb2/src/main/java/org/apache/jena/tdb2/solver/StageMatchTuple.java [hunk 2]
```diff
@@ -68,6 +70,17 @@ private static Iterator<BindingNodeId> access(NodeTupleTable nodeTupleTable, Bin
             iterMatches = x.iterator();
         }
 
+        // Add cancel check.
```
Comment (Aklakan) [inline jena-tdb2/src/main/java/org/apache/jena/tdb2/solver/StageMatchTuple.java:73]: A check is needed here for the following query on TDB2:
```
time curl http://localhost:3030/ds --data-urlencode 'query=PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> SELECT ?x { ?x rdfs:label ?y . ?y rdfs:label ?z }' --data-urlencode 'timeout=1'
```

Against this preloaded [TDB2 DBpedia dataset](https://maven.aksw.org/archiva/#artifact-details-download-content~internal/tdb2.org.aksw.data.text2sparql.2025/dbpedia/1.0.0) (~30GB)

File: jena-arq/src/main/java/org/apache/jena/sparql/exec/RowSetOps.java (hunk 1 above)
Comment (afs) [reply jena-arq/src/main/java/org/apache/jena/sparql/exec/RowSetOps.java]: Maybe it does not matter with thhis distructive operation but the cost of `stream()` is not trivial. 
`forEach` does not use `stream`.

Comment (afs) [reply jena-arq/src/main/java/org/apache/jena/sparql/exec/RowSetOps.java]: > Intent: Avoid memory copy.

`RowSetMem` rewind should not be a memory copy. It shares the rows array.

A rewindable RowSet (e.g. Mem) goes back to the beginning where as `forEach` continues the iteration.

**Comment by Aklakan** [comment]
Set to draft because I am still investigating this query on in memory datasets.

```sparql
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT ?x { ?x rdfs:label ?y . ?y rdfs:label ?z }
```

File: jena-arq/src/main/java/org/apache/jena/sparql/exec/RowSetOps.java (hunk 1 above)
Comment (Aklakan) [reply jena-arq/src/main/java/org/apache/jena/sparql/exec/RowSetOps.java]: Behavior so far:
* For non-RowSetMem instances counting would create an intermediate in-memory copy.
* The count for a RowSetMem instances would be the number of bindings in the row set - rather than the remaining bindings.

I added a the method `RowSetStream.forEachRemaining` - the stack trace for `RowSetOps.count` then becomes a delegate to the forEachRemaining method (with some boilerplate):

image

**Comment by Aklakan** [comment]
To summarize:

* Aborting the now lazy HashJoin has a dedicated test.
* For the empty join case, there is a dedicated test for `StageMatchTriple` based on a custom `GraphBase.find()` implementation that returns an infinite stream of matches.
* But: not sure how I to mock a similar test for `StageMatchTuple` in TDB1/2, because it requires some large dataset or mocking NodeIds. Here is a brief screencapture of the effect of this PR's code:

[CancelStageMatchTuple.webm](https://github.com/user-attachments/assets/8ef59741-6db3-472f-a392-cac811393423)

**Comment by Aklakan** [comment]
Hm, the long stack trace is not ideal - probably some additional exception catching is needed in the bridge between the `QueryIter(ator)` and plain iterator levels.

File: jena-arq/src/main/java/org/apache/jena/sparql/engine/iterator/QueryIterFilterExpr.java [hunk 3]
```diff
@@ -48,6 +49,9 @@ public Binding accept(Binding binding) {
             if ( expr.isSatisfied(binding, super.getExecContext()) )
                 return binding;
             return null;
+        } catch (QueryCancelledException ex) {
+            ex.addSuppressed(new RuntimeException("Query cancelled exception."));
+            throw ex;
```
Comment (Aklakan) [inline jena-arq/src/main/java/org/apache/jena/sparql/engine/iterator/QueryIterFilterExpr.java:54]: Should mitigate the case of ugly logging reported by @osma .
