### PR TITLE
Misc

### LINKED ISSUE #1678: Curious ignoral of JSON keys in JSON {} WHERE {}
### Version

4.7.0-SNAPSHOT

### What happened?

```
JSON {
    "x" : ?val1,
    "y" : ?val2
} WHERE {
  values (?val1 ?val2) {
    (1 2) 
  } 
}
```

```
[
  { 
    "val1" : 1 ,
    "val2" : 2
  }
]
```

**expected**
```
[
  { 
    "x" : 1 ,
    "y" : 2
  }
]
```

### Relevant output and stacktrace

_No response_

### Are you interested in making a pull request?

None

### PR DESCRIPTION
**Pull request by afs**
GitHub issue resolved #1678
Follow-up up after #1682

----

 - [x] Test coverage updated for the fix to #1678.
 - [x] Commits have been squashed to remove intermediate development commit messages.
 - [x] Key commit messages start with the issue number (GH-xxxx or JENA-xxxx)

By submitting this pull request, I acknowledge that I am making a contribution to the Apache Software Foundation under the terms and conditions of the [Contributor's Agreement](https://www.apache.org/licenses/contributor-agreements.html).

### CODE REVIEW

File: jena-arq/src/main/java/org/apache/jena/sparql/exec/JsonResults.java [hunk 1]
```diff
@@ -0,0 +1,112 @@
...
+ * <pre>
+ *    JSON {
+ *       "x": ?var1 ,
+ *       "y": ?var2
+ *    } WHERE {
+ *       ...
+ *    }
+ * </pre>
+ */
+public class JsonResults {
```
Comment (kinow) [inline jena-arq/src/main/java/org/apache/jena/sparql/exec/JsonResults.java:45]: Thank you!! I more or less had an idea of what was missing, but didn't know where to start looking for the right place to fix it.

File: jena-arq/src/main/java/org/apache/jena/sparql/exec/QueryExecDataset.java [hunk 2]
```diff
@@ -340,23 +337,9 @@ public JsonArray execJson() {
         checkNotClosed();
         if ( !query.isJsonType() )
             throw new QueryExecException("Attempt to get a JSON result from a " + labelForQuery(query) + " query");
-
         startQueryIterator();
-
-        JsonArray jsonArray = new JsonArray();
+        JsonArray jsonArray = JsonResults.results(queryIterator, query.getJsonMapping());
```
Comment (kinow) [inline jena-arq/src/main/java/org/apache/jena/sparql/exec/QueryExecDataset.java:341]: :ok_man:

**Review by kinow — APPROVED** [review]

File: jena-arq/src/main/java/org/apache/jena/sparql/exec/JsonResults.java (hunk 1 above)
Comment (afs) [reply jena-arq/src/main/java/org/apache/jena/sparql/exec/JsonResults.java:45]: The code is old with a slightly troubled history, and despite being in the new query execution code, it was a copy of the code before the QueryExec reworking. Looking at it now, there was duplication so some DRY applied.
