### PR TITLE
GH-2669: Test for rdf:datatype with incompatible RDF attributes

### LINKED ISSUE #2669: RDF/XML: The presence of both rdf:parseType and rdf:datatype on a property element should be an error
### Version

5.1.0

### What happened?

Test case:

```
<?xml version="1.0"?>

<rdf:RDF
    xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
    xml:base="http://base/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema#"
    xmlns:ex="http://example/">

  <rdf:Description rdf:about="s">
    <ex:property rdf:parseType="Literal" rdf:datatype="http://www.w3.org/2001/XMLSchema#integer">
      123
    </ex:property>
  </rdf:Description>
</rdf:RDF>
```

### Relevant output and stacktrace

_No response_

### Are you interested in making a pull request?

Yes

### PR DESCRIPTION
**Pull request by afs**
GitHub issue resolved #2669

----

 - [x] Tests are included.
 - [ ] Documentation change and updates are provided for the [Apache Jena website](https://github.com/apache/jena-site/)
 - [x] Commits have been squashed to remove intermediate development commit messages.
 - [x] Key commit messages start with the issue number (GH-xxxx)

By submitting this pull request, I acknowledge that I am making a contribution to the Apache Software Foundation under the terms and conditions of the [Contributor's Agreement](https://www.apache.org/licenses/contributor-agreements.html).

### CODE REVIEW

File: jena-arq/src/main/java/org/apache/jena/riot/lang/extra/TurtleJCC.java [hunk 1]
```diff
@@ -19,15 +19,26 @@
 package org.apache.jena.riot.lang.extra;
 
 import org.apache.jena.riot.*;
+import org.apache.jena.riot.lang.LangTurtle;
 
+/**
+ * This is not the normal Turtle parser.
+ * <p>
+ * This is a separate Turtle parser using JavaCC used as a comparision. The JavaCC
```
Comment (kinow) [inline jena-arq/src/main/java/org/apache/jena/riot/lang/extra/TurtleJCC.java:27]: s/comparision/comparison

File: jena-arq/src/main/java/org/apache/jena/riot/lang/extra/TurtleJavaccReaderRIOT.java [hunk 2]
```diff
@@ -36,8 +36,7 @@
 /**
  * Turtle parser, written using JavaCC.
  * This is not used normally.
- * It is slower than the RIOT {@link LangTurtle}.
- * It may not be up-to-date but at least in the codebase means it should be java-compatible.
+ * It is slower than the RIOT {@link LangTurtle} and has not be optimized for speed. Tokenizing is the bottleneck.
```
Comment (kinow) [inline jena-arq/src/main/java/org/apache/jena/riot/lang/extra/TurtleJavaccReaderRIOT.java:39]: s/be/been

**Review by kinow — APPROVED** [review]
