### PR TITLE
GH-1611: supply initial value for acceptHeaderGraph to requestConfig

### LINKED ISSUE #1611: CONSTRUCT query returns N-Triples when UI graph results choice is "Turtle".
### Version

4.6.1 (any 4.x.x)

### What happened?

Start Fuseki. 
`fuseki-server -v --mem /ds` but a UI created dataset behaves the same.
`-v` causes HTTP headers to be printed.

Go to the query form. The "Content Type (GRAPH)2 is set to Turtle.

Make a query:
```
PREFIX : <http://example>
CONSTRUCT { :s :p 123 } WHERE {}`
```
Results in "Response" area:

```
<http://example/s> <http://example/p> "123"^^<http://www.w3.org/2001/XMLSchema#integer> .
```
(The number isn't Turtle form 123)

The server shows
`Accept:              application/n-triples,*/*;q=0.9`
not 
`Accept:              text/turtle`

If you choose another format and then go back to Turtle, then reissue to query, it works correctly.

### Relevant output and stacktrace

_No response_

### Are you interested in making a pull request?

_No response_

### PR DESCRIPTION
**Pull request by OyvindLGjesdal**
GitHub issue resolved #1611 

Pull request Description:

The type is first set on change, due to being updated on the watch phase. Adding it to requestConfig sets it to turtle initially. contentTypeGraph variable was already set as the initial value for turtle, so reusing variable.

local fuseki with

Have also changed to other serializations sucessfully.

By submitting this pull request, I acknowledge that I am making a contribution to the Apache Software Foundation under the terms and conditions of the [Contributor's Agreement](https://www.apache.org/licenses/contributor-agreements.html).

----

See the [Apache Jena "Contributing" guide](https://github.com/apache/jena/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Comment by kinow** [comment]
Thanks @OyvindLGjesdal ! Change looks good, let me just check if it needs a test (I can write a quick one if so).

File: jena-fuseki2/jena-fuseki-ui/tests/unit/views/dataset/query.vue.spec.js [hunk 1]
```diff
@@ -0,0 +1,134 @@
...
+
+    // Test the initial values.
+    const yasqeOptions = wrapper.vm.yasqe.options
+    expect(yasqeOptions.showQueryButton).true
+    expect(yasqeOptions.resizeable).true
+
+    const requestConfig = yasqeOptions.requestConfig
+    expect(await requestConfig.endpoint).equals(FAKE_FUSEKI_URL)
+    // See issue https://github.com/apache/jena/issues/1611
+    expect(requestConfig.acceptHeaderGraph).equals(wrapper.vm.$data.contentTypeGraph)
```
Comment (kinow) [inline jena-fuseki2/jena-fuseki-ui/tests/unit/views/dataset/query.vue.spec.js:132]: Normally views are tested with e2e, but since the logic for YASQE/YASR is not well separated from the view, ended up having to write a unit test (will fix it someday).

The rest of the code is just preparing functions to mount the component, mocking things that are not available without a browser (like the `getBoundingClientRect` that's missing from jsdom), etc.

Then above this test verifies that the initial values are provided to YASQE< including the one for the accept header, which should guarantee we are defining it and YAS/R/QE/GUI should all use work as expected.

I haven't verified that the behaviour @afs reported is fixed (ran out of time today), but I can do that later, or maybe @afs can check it.

I pushed an extra commit with this test and with a formatting issue for spaces before colon (for consistency). Feel free to amend if there's anything wrong, @OyvindLGjesdal . And thanks for the PR!

**Review by kinow — APPROVED** [review]

**Comment by kinow** [comment]
(BTW, the unit test for a view does not affect the time to run the unit tests, which remains ridiculously fast, thanks to Vite:)

```
yarn run v1.22.19
$ vitest run --environment jsdom

 RUN  v1.6.0 /home/kinow/Development/java/jena/jena/jena-fuseki2/jena-fuseki-ui

 ✓ tests/unit/utils/query.spec.js (1)
 ✓ tests/unit/components/dataset/pagination.vue.spec.js (4)
 ✓ tests/unit/components/dataset/tablelisting.vue.spec.js (2)
 ✓ tests/unit/services/fuseki.service.spec.js (20)
 ✓ tests/unit/components/serverstatus.vue.spec.js (3)
 ✓ tests/unit/views/dataset/query.vue.spec.js (1) 323ms

 Test Files  6 passed (6)
      Tests  31 passed (31)
   Start at  16:02:43
   Duration  3.44s (transform 1.35s, setup 1ms, collect 3.45s, tests 767ms, environment 5.20s, prepare 1.73s)

Done in 4.50s.
```

**Review by afs — APPROVED** [review]

**Comment by afs** [comment]
LGTM - sorry for the delay reviewing.
