### PR TITLE
GH-2883: Fix for an NPE in OpAsQuery.

### LINKED ISSUE #2883: NPE in OpAsQuery
### Version

5.3.0-SNAPSHOT

### What happened?

The following query fails an `OpAsQuery` roundtrip due to an NPE:

```java
@Test
public void testAlgebra04() {
    String queryStr = """
        SELECT * {
          LATERAL {
              SELECT * {
                ?s a ?t
                FILTER EXISTS { SELECT * { ?s a ?c } }
              } LIMIT 1
          }
        }
        """;
    test_roundTripAlegbra(queryStr, Syntax.syntaxARQ);
  }
```
image

### Relevant output and stacktrace

```shell
java.lang.NullPointerException: Cannot invoke "org.apache.jena.sparql.expr.ExprTransform.transform(org.apache.jena.sparql.expr.ExprVar)" because "exprTransform" is null
	at org.apache.jena.sparql.syntax.syntaxtransform.QueryTransformOps.transformVarExprList(QueryTransformOps.java:238)
	at org.apache.jena.sparql.syntax.syntaxtransform.QueryTransformOps.mutateVarExprList(QueryTransformOps.java:208)
	at org.apache.jena.sparql.syntax.syntaxtransform.QueryTransformOps.mutateByQueryType(QueryTransformOps.java:143)
	at org.apache.jena.sparql.syntax.syntaxtransform.QueryTransformOps.transform(QueryTransformOps.java:72)
	at org.apache.jena.sparql.syntax.syntaxtransform.ApplyElementTransformVisitor.visit(ApplyElementTransformVisitor.java:222)
	at org.apache.jena.sparql.syntax.ElementWalker$EltWalker.visit(ElementWalker.java:200)
	at org.apache.jena.sparql.syntax.ElementSubQuery.visit(ElementSubQuery.java:52)
	at org.apache.jena.sparql.syntax.ElementWalker.walk(ElementWalker.java:37)
	at org.apache.jena.sparql.syntax.syntaxtransform.ElementTransformer.applyTransformation(ElementTransformer.java:80)
	at org.apache.jena.sparql.syntax.syntaxtransform.ElementTransformer.transformation(ElementTransformer.java:74)
	at org.apache.jena.sparql.syntax.syntaxtransform.ElementTransformer.transformation(ElementTransformer.java:65)
	at org.apache.jena.sparql.syntax.syntaxtransform.ElementTransformer.transform(ElementTransformer.java:57)
	at org.apache.jena.sparql.syntax.syntaxtransform.ElementTransformer.transform(ElementTransformer.java:47)
	at org.apache.jena.sparql.syntax.syntaxtransform.ExprTransformApplyElementTransform.transform(ExprTransformApplyElementTransform.java:46)
	at org.apache.jena.sparql.expr.ExprFunctionOp.apply(ExprFunctionOp.java:86)
	at org.apache.jena.sparql.algebra.walker.ApplyTransformVisitor.visit(ApplyTransformVisitor.java:426)
	at org.apache.jena.sparql.expr.ExprFunctionOp.visit(ExprFunctionOp.java:85)
	at org.apache.jena.sparql.algebra.walker.WalkerVisitor.visit(WalkerVisitor.java:279)
	at org.apache.jena.sparql.expr.ExprFunctionOp.visit(ExprFunctionOp.java:85)
	at org.apache.jena.sparql.algebra.walker.WalkerVisitor.walk(WalkerVisitor.java:91)
	at org.apache.jena.sparql.algebra.walker.Walker.walk$(Walker.java:104)
	at org.apache.jena.sparql.algebra.walker.Walker.walk$(Walker.java:100)
	at org.apache.jena.sparql.algebra.walker.Walker.walk(Walker.java:95)
	at org.apache.jena.sparql.algebra.walker.Walker.transform(Walker.java:211)
	at org.apache.jena.sparql.algebra.walker.Walker.transform(Walker.java:200)
	at org.apache.jena.sparql.algebra.walker.Walker.transform(Walker.java:194)
	at org.apache.jena.sparql.expr.ExprTransformer.transform(ExprTransformer.java:27)
	at org.apache.jena.sparql.syntax.syntaxtransform.ApplyElementTransformVisitor.transformExpr(ApplyElementTransformVisitor.java:241)
	at org.apache.jena.sparql.syntax.syntaxtransform.ApplyElementTransformVisitor.visit(ApplyElementTransformVisitor.java:77)
	at org.apache.jena.sparql.syntax.ElementWalker$EltWalker.visit(ElementWalker.java:75)
	at org.apache.jena.sparql.syntax.ElementFilter.visit(ElementFilter.java:35)
	at org.apache.jena.sparql.syntax.ElementWalker$EltWalker.visit(ElementWalker.java:121)
	at org.apache.jena.sparql.syntax.ElementGroup.visit(ElementGroup.java:120)
	at org.apache.jena.sparql.syntax.ElementWalker.walk(ElementWalker.java:37)
	at org.apache.jena.sparql.syntax.syntaxtransform.ElementTransformer.applyTransformation(ElementTransformer.java:80)
	at org.apache.jena.sparql.syntax.syntaxtransform.ElementTransformer.transformation(ElementTransformer.java:74)
	at org.apache.jena.sparql.syntax.syntaxtransform.ElementTransformer.transformation(ElementTransformer.java:65)
	at org.apache.jena.sparql.syntax.syntaxtransform.ElementTransformer.transform(ElementTransformer.java:52)
	at org.apache.jena.sparql.syntax.syntaxtransform.QueryTransformOps.mutateQueryPattern(QueryTransformOps.java:90)
	at org.apache.jena.sparql.syntax.syntaxtransform.QueryTransformOps.transform(QueryTransformOps.java:77)
	at org.apache.jena.sparql.syntax.syntaxtransform.ApplyElementTransformVisitor.visit(ApplyElementTransformVisitor.java:222)
	at org.apache.jena.sparql.syntax.ElementWalker$EltWalker.visit(ElementWalker.java:200)
	at org.apache.jena.sparql.syntax.ElementSubQuery.visit(ElementSubQuery.java:52)
	at org.apache.jena.sparql.syntax.ElementWalker$EltWalker.visit(ElementWalker.java:121)
	at org.apache.jena.sparql.syntax.ElementGroup.visit(ElementGroup.java:120)
	at org.apache.jena.sparql.syntax.ElementWalker$EltWalker.visit(ElementWalker.java:139)
	at org.apache.jena.sparql.syntax.ElementLateral.visit(ElementLateral.java:59)
	at org.apache.jena.sparql.syntax.ElementWalker$EltWalker.visit(ElementWalker.java:121)
	at org.apache.jena.sparql.syntax.ElementGroup.visit(ElementGroup.java:120)
	at org.apache.jena.sparql.syntax.ElementWalker.walk(ElementWalker.java:37)
	at org.apache.jena.sparql.syntax.syntaxtransform.ElementTransformer.applyTransformation(ElementTransformer.java:80)
	at org.apache.jena.sparql.syntax.syntaxtransform.ElementTransformer.transformation(ElementTransformer.java:74)
	at org.apache.jena.sparql.syntax.syntaxtransform.ElementTransformer.transformation(ElementTransformer.java:65)
	at org.apache.jena.sparql.syntax.syntaxtransform.ElementTransformer.transform(ElementTransformer.java:52)
	at org.apache.jena.sparql.algebra.OpAsQuery$Converter.fixupGroupsOfOne(OpAsQuery.java:438)
	at org.apache.jena.sparql.algebra.OpAsQuery$Converter.processQueryPattern(OpAsQuery.java:409)
	at org.apache.jena.sparql.algebra.OpAsQuery$Converter.convertInner(OpAsQuery.java:229)
	at org.apache.jena.sparql.algebra.OpAsQuery$Converter.convert(OpAsQuery.java:207)
	at org.apache.jena.sparql.algebra.OpAsQuery.asQuery(OpAsQuery.java:81)
	at org.apache.jena.sparql.algebra.TestOpAsQuery.queryToQuery(TestOpAsQuery.java:674)
	at org.apache.jena.sparql.algebra.TestOpAsQuery.test_roundTripAlegbra(TestOpAsQuery.java:650)
	at org.apache.jena.sparql.algebra.TestOpAsQuery.testAlgebra04(TestOpAsQuery.java:574)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
```

### Are you interested in making a pull request?

Yes

### PR DESCRIPTION
**Pull request by Aklakan**
GitHub issue resolved #2883 

Pull request Description: Changed a line to pass on an ExprTransform rather than null.

Notes for possible further improvements outside the scope of this PR:
* It may be the case that `ElementTransformer` needs to create an identity ExprTransform rather than passing null into the machinery.
* `QueryTransformOps.transformVarExprList` in my IDE warns that the `changed` flag is not used. Perhaps this needlessly creates clones of queries w.r.t. identity transforms.

----

 - [x] Tests are included.
 - [x] Commits have been squashed to remove intermediate development commit messages.
 - [x] Key commit messages start with the issue number (GH-xxxx)

By submitting this pull request, I acknowledge that I am making a contribution to the Apache Software Foundation under the terms and conditions of the [Contributor's Agreement](https://www.apache.org/licenses/contributor-agreements.html).

----

See the [Apache Jena "Contributing" guide](https://github.com/apache/jena/blob/main/CONTRIBUTING.md).

### CODE REVIEW

File: jena-arq/src/main/java/org/apache/jena/sparql/syntax/syntaxtransform/ExprTransformApplyElementTransform.java [hunk 1]
```diff
@@ -43,7 +43,7 @@ public ExprTransformApplyElementTransform(ElementTransform transform, boolean al
     @Override
     public Expr transform(ExprFunctionOp funcOp, ExprList args, Op opArg)
     {
-        Element el2 = ElementTransformer.transform(funcOp.getElement(), transform);
+        Element el2 = ElementTransformer.transform(funcOp.getElement(), transform, this);
```
Comment (Aklakan) [inline jena-arq/src/main/java/org/apache/jena/sparql/syntax/syntaxtransform/ExprTransformApplyElementTransform.java:46]: This is my actual fix attempt.

File: jena-arq/src/main/java/org/apache/jena/sparql/syntax/syntaxtransform/QueryTransformOps.java [hunk 2]
```diff
@@ -69,7 +69,7 @@ public static Query transform(Query query, ElementTransform transform, ExprTrans
         Query q2 = QueryTransformOps.shallowCopy(query);
         // Mutate the q2 structures which are already allocated and no other code can access yet.
 
-        mutateByQueryType(q2, transform, exprTransform);
+        mutateByQueryType(q2, exprTransform);
```
Comment (Aklakan) [inline jena-arq/src/main/java/org/apache/jena/sparql/syntax/syntaxtransform/QueryTransformOps.java:72]: Removed unused argument.

**Review by kinow — APPROVED** [review]

File: jena-arq/src/test/java/org/apache/jena/sparql/algebra/TestOpAsQuery.java [hunk 3]
```diff
@@ -482,6 +482,21 @@ public void testMinus02() {
                                                            "SELECT * { GRAPH ?g { { ?x ?y ?z FILTER(EXISTS { ?s ?p ?o }) } ?x ?y ?z } }",
                                                               syntaxARQ); }
 
+    @Test
```
Comment (afs) [inline jena-arq/src/test/java/org/apache/jena/sparql/algebra/TestOpAsQuery.java:485]: These EXISTS tests are about the ARQ extensions.

IIRC It's not about EXISTS, it's about subquery select expressions.

If that's right please use this test (insert at around L463):

```java
  @Test
  public void testSubQuery01() {
      test_roundTripQuery("SELECT ?z { SELECT ?x {  } }");
  }
```

The outer `SELECT ?z` stops the outer `SELECT` getting removed because `SELECT *` is a no-op.

Comment (Aklakan) [reply jena-arq/src/test/java/org/apache/jena/sparql/algebra/TestOpAsQuery.java:485]: Your query does not fail for me.

The fix is in 
```
    public Expr transform(ExprFunctionOp funcOp, ExprList args, Op opArg)
    {
        Element el2 = ElementTransformer.transform(funcOp.getElement(), transform, this);
    }
```
So the issue is related to (NOT) EXISTS *within* in a subquery.
Also note that, the transform is an `ElementTransform` - so `SELECT * { ?s a ?c }` is different from `?s a ?c` - although the Op would be the same.

I reduced the query to this:
```
SELECT ?s {
  SELECT ?s {
    ?s a ?t
    FILTER EXISTS { SELECT * { ?s a ?c } }
  }
}
```

File: jena-arq/src/test/java/org/apache/jena/sparql/algebra/TestOpAsQuery.java [hunk 4]
```diff
@@ -329,6 +329,11 @@ public void testSubQuery3() {
         test_roundTripQuery(query) ;
     }
 
+    @Test
+    public void testSubQuery4() {
```
Comment (Aklakan) [inline jena-arq/src/test/java/org/apache/jena/sparql/algebra/TestOpAsQuery.java:333]: I added this test case for completeness - but it did not fail.

**Comment by Aklakan** [comment]
My change is in here:

```sparql
    public Expr transform(ExprFunctionOp funcOp, ExprList args, Op opArg)
    {
        Element el2 = ElementTransformer.transform(funcOp.getElement(), transform, this);
    }
```

So the issue is related to (NOT) EXISTS when there is a subquery.
Also note that, the transform is an ElementTransform - so SELECT * { ?s a ?c } is treated different than ?s a ?c - although the Op would be the same.

I reduced the query to this:

```sparql
SELECT ?x {
  SELECT ?x { # <-- NPE disappears when removing this sub select.
    ?x a ?y
    FILTER EXISTS { SELECT * { ?y a ?z } }
  }
}
```

I silghtly updated the test cases.

**Comment by Aklakan** [comment]
I converted to draft for now because it seems there are some more issues related to how ExprFunctionOp are handled - I added another example query that breaks to https://github.com/apache/jena/issues/2883#issuecomment-2527919893

**Comment by Aklakan** [comment]
I updated the code that handles ExprFunctionOp that when the Element is absent then it will be derived from the algebra.

File: jena-arq/src/main/java/org/apache/jena/sparql/syntax/syntaxtransform/ExprTransformApplyElementTransform.java [hunk 5]
```diff
@@ -43,7 +44,15 @@ public ExprTransformApplyElementTransform(ElementTransform transform, boolean al
...
-        Element el2 = ElementTransformer.transform(funcOp.getElement(), transform);
+        // If the element is null then an attempt is made to obtain it from the algebra.
+        // A given element takes precedence over the algebra.
+        Element el1 = funcOp.getElement();
+        if (el1 == null) {
+            Op op = funcOp.getGraphPattern();
+            el1 = op == null ? null : OpAsQuery.asElement(op);
+        }
+        // ElementTransformer will warn should it happen that null is passed to it.
+        Element el2 = ElementTransformer.transform(el1, transform, this);
```
Comment (Aklakan) [inline jena-arq/src/main/java/org/apache/jena/sparql/syntax/syntaxtransform/ExprTransformApplyElementTransform.java:55]: This is now the updated actual fix - together with the introduction of `OpAsQuery.asElement`.

File: jena-arq/src/main/java/org/apache/jena/sparql/syntax/syntaxtransform/ExprTransformApplyElementTransform.java (hunk 1 above)
Comment (Aklakan) [reply jena-arq/src/main/java/org/apache/jena/sparql/syntax/syntaxtransform/ExprTransformApplyElementTransform.java]: The fix is extended with a few additional line in a separate comment. Closing this one.
