### PR TITLE
GH-2881: Mitigate cases of open iterators when cancelling queries.

### LINKED ISSUE #2881: Open iterators when cancelling queries
### Version

5.3.0-SNAPSHOT

### What happened?

Sometimes when cancelling queries warnings are logged such as:
```
Open iterator: QueryIterPeek/123
Open iterator: QueryIterSingleton/456
```

So far I noticed this to happen when BGPs and UNIONs are involved, but this may not be exhaustive.

It turns out that not all the iterator construction in ARQ is performed truly lazy, which causes some parts of the code to leave iterators open if an exception happens during the iterator construction.

After investigation it seems that the warnings should (usually) be harmless, because the `QueryIter`s are tracked in the `ExecutionContext` and thus eventually become closed without leaking resources.

However, seeing these warnings suggests that resources *might* be leaked - so this is an issue that IMO should be fixed.

See the PR for a test case and the proposed fixes.

### Relevant output and stacktrace

_No response_

### Are you interested in making a pull request?

Yes

### PR DESCRIPTION
**Pull request by Aklakan**
GitHub issue resolved #2881 

Pull request Description:
- Added a test case that should emit warnings without the fixes (the tests do not fail otherwise)
- Adds exception handling to OpUnion and StageGeneratorGeneric, mainly to cope with concurrent QueryCancelledException.

----

 - [x] Tests are included.
 - [x] Commits have been squashed to remove intermediate development commit messages.
 - [x] Key commit messages start with the issue number (GH-xxxx)

By submitting this pull request, I acknowledge that I am making a contribution to the Apache Software Foundation under the terms and conditions of the [Contributor's Agreement](https://www.apache.org/licenses/contributor-agreements.html).

----

See the [Apache Jena "Contributing" guide](https://github.com/apache/jena/blob/main/CONTRIBUTING.md).

### CODE REVIEW

File: jena-arq/src/main/java/org/apache/jena/sparql/engine/main/StageGeneratorGeneric.java [hunk 1]
```diff
@@ -65,7 +86,7 @@ protected QueryIterator execute(BasicPattern pattern, ReorderTransformation reor
                 QueryIterPeek peek = QueryIterPeek.create(input, execCxt) ;
                 // And now use this one
                 input = peek ;
-                Binding b = peek.peek() ;
+                Binding b = closeOnException(peek::peek, peek) ;
```
Comment (afs) [inline jena-arq/src/main/java/org/apache/jena/sparql/engine/main/StageGeneratorGeneric.java:89]: It looks to me like `QueryIterPeek` should be updated to handle cancellations rather than putting execution costs into the main path.

File: jena-arq/src/main/java/org/apache/jena/sparql/engine/main/StageGeneratorGeneric.java [hunk 2]
```diff
@@ -49,12 +53,29 @@ public QueryIterator execute(BasicPattern pattern, QueryIterator input, Executio
...
+     */
     protected QueryIterator execute(BasicPattern pattern, ReorderTransformation reorder,
                                     QueryIterator input, ExecutionContext execCxt) {
         Explain.explain(pattern, execCxt.getContext()) ;
 
-        if ( ! input.hasNext() )
-            return input ;
+        QueryIterator originalInput = input;
+        if ( closeOnException(() -> !originalInput.hasNext(), originalInput) )
+            return originalInput ;
```
Comment (afs) [inline jena-arq/src/main/java/org/apache/jena/sparql/engine/main/StageGeneratorGeneric.java:78]: The `input` should be closed in a cancel. If it is not then something is missing elsewhere. 

See the issue #2881 for discussion about inverting the overall design to have explicit declaration and management of resources that have clear-up.

Comment (Aklakan) [reply jena-arq/src/main/java/org/apache/jena/sparql/engine/main/StageGeneratorGeneric.java:78]: Right, I think this check is superfluous.

File: jena-arq/src/main/java/org/apache/jena/sparql/engine/main/StageGeneratorGeneric.java (hunk 1 above)
Comment (Aklakan) [reply jena-arq/src/main/java/org/apache/jena/sparql/engine/main/StageGeneratorGeneric.java:89]: Mhm, an exception during `iter.peek()` could close `iter`.

File: jena-arq/src/main/java/org/apache/jena/sparql/engine/iterator/QueryIterPeek.java [hunk 3]
```diff
@@ -25,27 +25,34 @@
...
-    public Binding peek() 
+    public Binding peek()
     {
         if ( closed ) return null ;
-        if ( ! hasNextBinding() )
-            return null ;
+        try {
+            if ( ! hasNextBinding() )
+                return null ;
+        } catch (Exception e) {
```
Comment (Aklakan) [inline jena-arq/src/main/java/org/apache/jena/sparql/engine/iterator/QueryIterPeek.java:50]: Perhaps having the try-catch block in `StageGeneratorGeneric.execute` is slightly better. Essentially, a method that returns a QueryIterator should close its own already allocated resources early in case of a failure. It feels not totally clean having peek() deal with an exception but not hasNextBinding / moveToNext.

The thing is, that even if an iterator's hasNextBinding / moveToNext raise an exception, then this iterator will usually connected to the 'root' iterator. The query execution will catch an exception and close the root iterator which will propagate to its children and only then a check for dangling resources is done.

The problem is that StageGeneratorGeneric creates an QueryIterPeek, then calls peek which fails, and then the already registered iterator is left dangling - so its not really an issue of peek().

File: jena-arq/src/main/java/org/apache/jena/sparql/engine/main/StageGeneratorGeneric.java (hunk 2 above)
Comment (Aklakan) [reply jena-arq/src/main/java/org/apache/jena/sparql/engine/main/StageGeneratorGeneric.java]: Removed the check again.

File: jena-arq/src/main/java/org/apache/jena/sparql/engine/iterator/QueryIterPeek.java (hunk 3 above)
Comment (Aklakan) [reply jena-arq/src/main/java/org/apache/jena/sparql/engine/iterator/QueryIterPeek.java]: I moved the try-catch block back to StageGeneratorGeneric because based on my previous argument it would be the appropriate place.

File: jena-arq/src/main/java/org/apache/jena/sparql/engine/main/iterator/QueryIterUnion.java [hunk 4]
```diff
@@ -51,21 +50,51 @@ public QueryIterUnion(QueryIterator input,
...
+                    } else {
+                        if (subOpIt.hasNext()) {
+                            Op subOp = subOpIt.next();
+                            qIter = QC.execute(subOp, binding, getExecContext());
+                        } else {
+                            return false;
+                        }
+                    }
+                }
+            }
```
Comment (Aklakan) [inline jena-arq/src/main/java/org/apache/jena/sparql/engine/main/iterator/QueryIterUnion.java:86]: Making the nextStage() method of `QueryIterUnion` truly lazy removes the need for try-catch blocks: Sub-iterators are only opened when needed, and if a creation fails then there are no previously opened resources that need to be cleaned up.

**Review by afs — APPROVED** [review]
