### PR TITLE
Permit injecting UNDEF in ParameterizedSparqlString (GH-3268)

### LINKED ISSUE #3268: Support for `UNDEF` in `ParameterizedSparqlString` VALUES methods
### Version

5.4

## Description  
As I understand, in SPARQL 1.1, the `UNDEF` keyword in a `VALUES` clause represents an unbound binding (i.e. `null`). However, when I'm calling any of the following methods in  `org.apache.jena.query.ParameterizedSparqlString` with a `null` element, a `NullPointerException` is thrown:  
```java
setValues(String valueName, Collection<? extends org.apache.jena.rdf.model.RDFNode> items)
setValues(String valueName, org.apache.jena.rdf.model.RDFNode item)
setValues(Map<String, Collection<? extends org.apache.jena.rdf.model.RDFNode>> itemsMap)
```
There is also no existing `RDFNode` implementation that represents the SPARQL keyword `UNDEF`. According to the SPARQL 1.1 specification, `UNDEF` must be allowed in a VALUES clause to represent an unbound binding.

## Actual Behavior
- A `NullPointerException` occurs
- No way to explicitly represent the `UNDEF` keyword via the API

## Expected Behavior
- No `NullPointerException` is thrown
- The generated query is valid SPARQL:
```sparql
VALUES (?x ?y) {
  (:uri1 1)
  (:uri2 UNDEF)
}
```

## Possible Solutions
1. Introduce an `UndefRDFNode`
    - Create a class `UndefRDFNode` implements `RDFNode` whose `toString()` returns "UNDEF".
    - `ParameterizedSparqlString` detects instances of `UndefRDFNode` and render them as `UNDEF`.
2. Treat `null` as `UNDEF`
    - Modify all `setValues` methods to catch `null` entries and output `UNDEF` instead of throwing an exception.
    - Pros: No new class required.
    - Cons: Overloading `null` may be confusing in other contexts.
     
3. Reuse an existing Node type
    - Investigate if `Node.ANY` or another core Node can be repurposed to mean unbound.
    - Please note: `Node.ANY` is intended for pattern matching, not unbound results, so semantics differ.

## Tests
Add unit tests for each overload of `setValues` method to verify that the correct results are returned:
- Single-variable `UNDEF` case
- Mixed bindings, e.g. `( :uri1 1 )`, `( :uri2 UNDEF )`
- Multi-variable rows containing `UNDEF`

## References
- Apache JIRA: [JENA-1750](https://issues.apache.org/jira/browse/JENA-1750)
- SPARQL 1.1 Query Language: [VALUES clause](https://www.w3.org/TR/sparql11-query/#inline-data)

### Are you interested in contributing a solution yourself?

None

### PR DESCRIPTION
**Pull request by rvesse**
This commit adds the ability for `ParameterizedSparqlString` to support injecting the `UNDEF` keyword into `VALUES` clauses as needed.  A new `undef()` method is added to the class that provides access to a special instance level constant `RDFNode` that is used to indicate that the caller wants to inject `UNDEF`.

Under the hood this is just a wrapper around a `Node` constant but due to the `setValues()`/`setRowValues()` part of the API working in `RDFNode`'s rather than `Node`'s went with this approach.  I considered refactoring further to allow that part of the API to take `Node` and `RDFNode` interchangeably **but** given the limitations of Java type erasure generics (several of the methods in that part of the API use `Collection<? extends RDFNode>` and similar) that would effectively introduce a breaking API change so probably best done for a major release in a separate PR.

GitHub issue resolved #3268 

----

 - [x] Tests are included.
 - [ ] Documentation change and updates are provided for the [Apache Jena website](https://github.com/apache/jena-site/)
 - [x] Commits have been squashed to remove intermediate development commit messages.
 - [x] Key commit messages start with the issue number (GH-xxxx)

By submitting this pull request, I acknowledge that I am making a contribution to the Apache Software Foundation under the terms and conditions of the [Contributor's Agreement](https://www.apache.org/licenses/contributor-agreements.html).

----

See the [Apache Jena "Contributing" guide](https://github.com/apache/jena/blob/main/CONTRIBUTING.md).

### CODE REVIEW

File: jena-arq/src/test/java/org/apache/jena/query/TestParameterizedSparqlString.java [hunk 1]
```diff
@@ -2093,6 +2107,23 @@ public void test_set_values_multiple_variables() {
...
+        String str = "SELECT * WHERE { VALUES (?p ?o) {?vars} ?s ?p ?o }";
+        ParameterizedSparqlString pss = new ParameterizedSparqlString(str);
+        List<RDFNode> vars = new ArrayList<>();
+        vars.add(ResourceFactory.createProperty("http://example.org/prop_A"));
+        vars.add(pss.undef());
+        pss.setValues("vars", vars);
+
+        String exp = "SELECT * WHERE { VALUES (?p ?o) {(<http://example.org/prop_A> UNDEF)} ?s ?p ?o }";
+        String res = pss.toString();
+        //System.out.println("Exp: " + exp);
```
Comment (afs) [inline jena-arq/src/test/java/org/apache/jena/query/TestParameterizedSparqlString.java]: Remove development code?

File: jena-arq/src/test/java/org/apache/jena/query/TestParameterizedSparqlString.java [hunk 2]
```diff
@@ -2001,6 +2001,20 @@ public void test_set_values_item2() {
...
+    @Test
+    public void test_set_values_undef() {
+        // Tests a single value being added using '$' variable syntax - always adding parenthesis.
+        String str = "SELECT * WHERE { VALUES $o {$objs} $s $p $o }";
+        ParameterizedSparqlString pss = new ParameterizedSparqlString(str);
+        pss.setValues("objs", pss.undef());
+
+        String exp = "SELECT * WHERE { VALUES $o {(UNDEF)} $s $p $o }";
+        String res = pss.toString();
+        //System.out.println("Exp: " + exp);
```
Comment (afs) [inline jena-arq/src/test/java/org/apache/jena/query/TestParameterizedSparqlString.java]: Remove development code?

File: jena-arq/src/test/java/org/apache/jena/query/TestParameterizedSparqlString.java (hunk 1 above)
Comment (rvesse) [reply jena-arq/src/test/java/org/apache/jena/query/TestParameterizedSparqlString.java]: I was just copying pasting existing tests, a lot of the tests in this test class have these commented out debugging statements,  happy to clean those up

Comment (afs) [reply jena-arq/src/test/java/org/apache/jena/query/TestParameterizedSparqlString.java]: Might be the moment to do so!

Comment (rvesse) [reply jena-arq/src/test/java/org/apache/jena/query/TestParameterizedSparqlString.java]: Have now cleaned all those up

Comment (afs) [reply jena-arq/src/test/java/org/apache/jena/query/TestParameterizedSparqlString.java]: Thansk - I have been doing similar across the code base during preparation for Jena6.

**Review by afs — APPROVED** [review]
