### PR TITLE
GH-1670: Close Iterator

### LINKED ISSUE #1670: listDeclaredProperties() tooks more and more time to execute
### Version

4.6.1

### What happened?

The more you call `org.apache.jena.ontology.OntClass.listDeclaredProperties()` the more it tooks time to execute. This method becomes more and more slower. 

```java
    public static void main(String[] args)
    {
        var ontModel = ModelFactory.createOntologyModel();
        ontModel.read("file:///home/xxx/myOntology.owl");
        var firstClass = ontModel.listClasses().toList().get(0);
        for (int i = 0; i < 1000; i++) {
            var sw = Stopwatch.createStarted();
            firstClass.listDeclaredProperties().toList();
            System.out.println(i + ":" + sw.elapsed());
        }
    }
```

Note that it's the same behaviour even if different classes are used.

### Relevant output and stacktrace

```shell
0:PT0.055325154S
1:PT0.053741853S
2:PT0.054867645S
3:PT0.070754346S
4:PT0.079063488S
5:PT0.093237643S
6:PT0.137334963S
7:PT0.142026425S
8:PT0.116740488S
9:PT0.146456742S
10:PT0.14737348S
11:PT0.167979274S
12:PT0.17817369S
13:PT0.167179256S
14:PT0.185085727S
15:PT0.257568758S
16:PT0.22520317S
17:PT0.222611836S
18:PT0.244964476S
19:PT0.423808625S
20:PT0.522226384S
21:PT0.258701954S
22:PT0.290371277S
23:PT0.299436569S
24:PT0.348829765S
25:PT0.385084312S
26:PT0.414980109S
27:PT0.432318751S
28:PT0.358993124S
29:PT0.536478478S
30:PT0.400525157S
31:PT0.405575171S
32:PT0.43975006S
33:PT0.588212486S
34:PT0.504768661S
35:PT0.47386472S
36:PT0.491770105S
37:PT0.572203136S
38:PT0.750634939S
39:PT0.729411756S
40:PT0.582904746S
41:PT0.741269613S
42:PT0.607716705S
43:PT0.648015162S
44:PT0.827245457S
45:PT1.316798135S
46:PT0.656879154S
47:PT1.087542556S
48:PT0.77007276S
49:PT0.837496052S
50:PT0.821686962S
51:PT0.945059914S
52:PT0.739706686S
53:PT0.976433163S
54:PT0.882605854S
55:PT0.957281903S
56:PT0.898449329S
57:PT1.122094518S
58:PT1.176675862S
59:PT1.082373224S
60:PT0.964563953S
61:PT1.234236324S
62:PT1.249757814S
63:PT1.093008794S
64:PT1.18456982S
65:PT2.164066478S
66:PT1.661992769S
67:PT1.859415001S
68:PT1.901422771S
69:PT1.815900642S
70:PT1.993360015S
71:PT2.352348544S
72:PT2.910944229S
73:PT2.119100313S
74:PT1.698402973S
75:PT2.345774948S
76:PT1.801463752S
77:PT2.790495351S
78:PT2.678398909S
79:PT2.765297809S
80:PT2.157752931S
81:PT2.218126379S
82:PT2.262952311S
83:PT2.334162855S
84:PT2.333061817S
85:PT2.376076411S
86:PT2.531165826S
87:PT2.54454447S
88:PT2.464155482S
89:PT2.51932124S
90:PT2.462913887S
91:PT2.671357237S
92:PT2.837611196S
93:PT3.27071915S
94:PT2.806180608S
95:PT3.372608549S
96:PT3.318608036S
97:PT3.099067653S
98:PT3.302158362S
99:PT3.45700879S
100:PT3.403054836S
101:PT3.530809466S
102:PT3.68405691S
103:PT3.653777304S
104:PT3.882070433S
105:PT3.749791199S
106:PT3.859925454S
107:PT3.872080541S
108:PT3.725115198S
109:PT4.205663907S
110:PT4.345577385S
111:PT4.294628296S
112:PT4.01872168S
113:PT4.270718528S
114:PT4.539190868S
115:PT4.395004512S
116:PT4.565366837S
117:PT4.729587654S
118:PT4.678631135S
119:PT4.823886962S
120:PT4.713439297S
121:PT4.800807658S
122:PT4.982632552S
```

### Are you interested in making a pull request?

None

### PR DESCRIPTION
**Pull request by afs**
GitHub issue resolved #1670

Close iterators.

----

 - [x] Commits have been squashed to remove intermediate development commit messages.
 - [x] Key commit messages start with the issue number (GH-xxxx or JENA-xxxx)

By submitting this pull request, I acknowledge that I am making a contribution to the Apache Software Foundation under the terms and conditions of the [Contributor's Agreement](https://www.apache.org/licenses/contributor-agreements.html).

----

See the [Apache Jena "Contributing" guide](https://github.com/apache/jena/blob/main/CONTRIBUTING.md).

### CODE REVIEW

File: jena-geosparql/src/main/java/org/apache/jena/geosparql/spatial/property_functions/GenericSpatialPropertyFunction.java [hunk 1]
```diff
@@ -126,12 +127,12 @@ private boolean checkBound(ExecutionContext execCxt, Node subject) {
...
                     spatialTriples.addIterator(iter);
-                }
+                });
             } else {
                 //Check for Geo predicates against the feature when no geometry literals found.
                 if (graph.contains(subject, SpatialExtension.GEO_LAT_NODE, null) && graph.contains(subject, SpatialExtension.GEO_LON_NODE, null)) {
-                    Node lat = graph.find(subject, SpatialExtension.GEO_LAT_NODE, null).next().getObject();
-                    Node lon = graph.find(subject, SpatialExtension.GEO_LON_NODE, null).next().getObject();
+                    Node lat = G.getOneSP(graph, subject, SpatialExtension.GEO_LAT_NODE);
+                    Node lon = G.getOneSP(graph, subject, SpatialExtension.GEO_LON_NODE);
```
Comment (kinow) [inline jena-geosparql/src/main/java/org/apache/jena/geosparql/spatial/property_functions/GenericSpatialPropertyFunction.java:135]: :ok_man:

**Review by kinow — APPROVED** [review]
