### PR TITLE
GH-1432: Fix for adding text data after TDB2 compaction

### LINKED ISSUE #1432: Fuseki stops updating lucene indexes after /$/compact/
### Version

4.5.0

### What happened?

We have been tirelessly trying to figure out why we couldn't find data anymore through text:query. Now it turns out everything works fine but as soon as you call /$/compact , new or updated data doesn't get indexed anymore to lucene. Happens on 4.1 to 4.5.

We run the compact like this
`
        String[] compactCMD = {
            "curl", "-u", "admin:" + appProperties.getFuseki().getAdminPassword(), "-XPOST",
            appProperties.getFuseki().getUrl() + "/$/compact/fedora?deleteOld=true"
        };
        var compactProcess = Runtime.getRuntime().exec(compactCMD);
`

### Relevant output and stacktrace

```shell
@prefix :       <http://base/#> .
@prefix fuseki: <http://jena.apache.org/fuseki#> .
@prefix ja:     <http://jena.hpl.hp.com/2005/11/Assembler#> .
@prefix rdf:    <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs:   <http://www.w3.org/2000/01/rdf-schema#> .
@prefix tdb2:   <http://jena.apache.org/2016/tdb#> .
@prefix text:   <http://jena.apache.org/text#> .
@prefix dc:     <http://purl.org/dc/elements/1.1/> .
@prefix ibron:  <http://surf.nl/ibron/item/2020/07/> .

tdb2:GraphTDB  rdfs:subClassOf  ja:Model .

ja:ModelRDFS  rdfs:subClassOf  ja:Model .

ja:RDFDatasetSink  rdfs:subClassOf  ja:RDFDataset .

<http://jena.hpl.hp.com/2008/tdb#DatasetTDB>
        rdfs:subClassOf  ja:RDFDataset .

tdb2:GraphTDB2  rdfs:subClassOf  ja:Model .

<http://jena.apache.org/text#TextDataset>
        rdfs:subClassOf  ja:RDFDataset .

ja:RDFDatasetZero  rdfs:subClassOf  ja:RDFDataset .

:service_tdb_all  rdf:type            fuseki:Service ;
        rdfs:label                    "TDB2 fedora" ;
        fuseki:dataset                :text_dataset ;
        fuseki:name                   "fedora" ;
        fuseki:serviceQuery           "query" , "" , "sparql" ;
        fuseki:serviceReadGraphStore  "get" ;
        fuseki:serviceReadWriteGraphStore
                "data" ;
        fuseki:serviceUpdate          "" , "update" ;
        fuseki:serviceUpload          "upload" .

ja:ViewGraph  rdfs:subClassOf  ja:Model .

ja:GraphRDFS  rdfs:subClassOf  ja:Model .

tdb2:DatasetTDB  rdfs:subClassOf  ja:RDFDataset .

<http://jena.hpl.hp.com/2008/tdb#GraphTDB>
        rdfs:subClassOf  ja:Model .

ja:DatasetTxnMem  rdfs:subClassOf  ja:RDFDataset .

tdb2:DatasetTDB2  rdfs:subClassOf  ja:RDFDataset .

ja:RDFDatasetOne  rdfs:subClassOf  ja:RDFDataset .

ja:MemoryDataset  rdfs:subClassOf  ja:RDFDataset .

:text_dataset rdf:type text:TextDataset ;
  text:dataset :tdb_dataset_readwrite ;
  text:index <#lucene> ;
  .

:tdb_dataset_readwrite rdf:type       tdb2:DatasetTDB2 ;
        tdb2:location  "/fuseki-base/databases/fedora" .

ja:DatasetRDFS  rdfs:subClassOf  ja:RDFDataset .

<#lucene> a text:TextIndexLucene ;
    text:directory <file:/fuseki-base/databases/lucene-fedora> ;
    text:storeValues true ;
    text:entityMap <#entity-map> ;
    .

<#entity-map> a text:EntityMap ;
    text:entityField "uri" ;
    # text:graphField "graph" ; ## enable graph-specific indexing
    text:defaultField "text" ; ## Must be defined in the text:map
    text:uidField "uid" ;
    # text:langField "lang" ;
    text:map (
         [ text:field "text" ; text:predicate dc:title ]
         [ text:field "text" ; text:predicate ibron:subTitle ]
         )
```

### Are you interested in making a pull request?

_No response_

### PR DESCRIPTION
**Pull request by afs**
GitHub issue resolved #1432

Pull request Description:

jena-text integrates with TDB2 by adding a `TransactionalComponent` and becoming part of the TDB/DBOW transaction system.

The bug is that the added `TransactionalComponent` is in the storage database, not the switchable database. The storage database is rewritten and rebuilt by a compaction and the added component gets lost.

----

 - [x] Tests are included.
 - [N/A] Documentation change and updates are provided for the [Apache Jena website](https://github.com/apache/jena-site/)
 - [x] Commits have been squashed to remove intermediate development commit messages.
 - [x] Key commit messages start with the issue number (GH-xxxx or JENA-xxxx)

By submitting this pull request, I acknowledge that I am making a contribution to the Apache Software Foundation under the terms and conditions of the [Contributor's Agreement](https://www.apache.org/licenses/contributor-agreements.html).

----

See the [Apache Jena "Contributing" guide](https://github.com/apache/jena/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Comment by afs** [comment]
This PR is a complete fix. 

There maybe a more principled way to add `TransactionalComponent` that automates them being copied into the new storage database transaction subsystem.

That can follow later.

File: jena-text/src/main/java/org/apache/jena/query/text/DatasetGraphText.java [hunk 1]
```diff
@@ -166,12 +166,33 @@ public void begin(TxnType txnType) {
...
+
+    private void tdb2Setup(TransactionCoordinator coord) {
+        // Does not overlap with the ids used by TDB2.
+        byte[] componentID = { 2,4,6,10 } ;
+        TransactionalComponent tc = new TextIndexDB(ComponentId.create(null, componentID), textIndex);
+        coord.modifyConfig(()->coord.add(tc));
+        commitAction = delegateCommit;
+        abortAction = delegateAbort;
+
+    }
```
Comment (kinow) [inline jena-text/src/main/java/org/apache/jena/query/text/DatasetGraphText.java:194]: From the PR description, I think the fix is mainly in this part. I don't understand everything involved here, but couldn't find anything that looked wrong. +1 :+1:  Thanks!

**Review by kinow — APPROVED** [review]

File: jena-text/src/main/java/org/apache/jena/query/text/DatasetGraphText.java (hunk 1 above)
Comment (afs) [reply jena-text/src/main/java/org/apache/jena/query/text/DatasetGraphText.java:194]: Yes - small fix, more changes in tests. Then some reshuffle (something bad when on with formatting at some point) - broken into separate commits.
