### PR TITLE
GH-1688 Fix possible incomplete results with service enhaner caching + bulk

### LINKED ISSUE #1688: Service Enhancer: Cache hits with empty result sets may cut off bulk request results
### Version

4.7.0-SNAPSHOT

### What happened?

Credits once again to @LorenzBuehmann for spotting this.

The second execution of a query making use of caching such as below may return an incomplete result set. The reason is due to a bug in the service enhancer's `QueryIterServiceBulk`: If a cache lookup detects that an empty result set has to be served then the returned empty iterator is not properly registered in the overall result iterator.

```sparql
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT * {
  { SELECT * { ?s a rdfs:Resource } ORDER BY ?s } 

  # Evaluation of this following pattern on the example data occasionally
  # creates cache entries with empty result sets which in turn
  # cause overall result sets based on serving data from cache becoming cut off
  SERVICE <loop:cache:bulk+20> { ?s rdfs:label ?l }
}
```

Example data:
```
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
<urn:example:aa> a rdfs:Resource .
<urn:example:ab> a rdfs:Resource ; rdfs:label "ab" .
<urn:example:ac> a rdfs:Resource .
<urn:example:ad> a rdfs:Resource ; rdfs:label "ad" .
```

### Relevant output and stacktrace

* On the first execution (uncached) the query will correctly return two results (for the labels "ab", "ad").
* On the second execution (cached) the query will incorrectly return zero results. This is because the empty result sets from cache - such as that of `<urn:example:aa>` - are internally incorrectly processed causing the overall result set to become unexpectedly cut off.

### Are you interested in making a pull request?

Yes

### PR DESCRIPTION
**Pull request by Aklakan**
GitHub issue resolved #1688

Pull request Description: Fixes registration of an empty iterator in case a cache hit reveals an empty result set.

----

 - [x] Tests are included.
 - ~~[ ] Documentation change and updates are provided for the [Apache Jena website](https://github.com/apache/jena-site/)~~
 - [x] Commits have been squashed to remove intermediate development commit messages.
 - [x] Key commit messages start with the issue number (GH-xxxx or JENA-xxxx)

By submitting this pull request, I acknowledge that I am making a contribution to the Apache Software Foundation under the terms and conditions of the [Contributor's Agreement](https://www.apache.org/licenses/contributor-agreements.html).

----

See the [Apache Jena "Contributing" guide](https://github.com/apache/jena/blob/main/CONTRIBUTING.md).

### CODE REVIEW

File: jena-extras/jena-serviceenhancer/src/test/java/org/apache/jena/sparql/service/enhancer/impl/TestServiceEnhancerMisc.java [hunk 1]
```diff
@@ -462,4 +471,55 @@ public void testNormalization01() {
...
+     * that involves contributions of cached empty result sets works as expected.
+     * Without the fix corresponding to this issues this test fails.
+     *
+     * @implNote This test case makes use of a dataset where only a few resources have labels.
+     * The test query caches the labels of all resources which means that most cache entries
+     * have empty results.
+     */
+    @Test
+    public void testEmptyResultSetContribution() {
+        String dataStr = String.join(StandardSystemProperty.LINE_SEPARATOR.value(),
```
Comment (afs) [inline jena-extras/jena-serviceenhancer/src/test/java/org/apache/jena/sparql/service/enhancer/impl/TestServiceEnhancerMisc.java:488]: Not critical but why not "\n"? SPARQL is a web language.

File: jena-extras/jena-serviceenhancer/src/test/java/org/apache/jena/sparql/service/enhancer/impl/TestServiceEnhancerMisc.java [hunk 2]
```diff
@@ -462,4 +471,55 @@ public void testNormalization01() {
...
+            "PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>",
+            "<urn:example:00> a rdfs:Resource .",
+            "<urn:example:01> a rdfs:Resource .",
+            "<urn:example:02> a rdfs:Resource .",
+            "<urn:example:03> a rdfs:Resource .",
+            "<urn:example:04> a rdfs:Resource ; rdfs:label \"04\" .",
+            "<urn:example:05> a rdfs:Resource .",
+            "<urn:example:06> a rdfs:Resource .",
+            "<urn:example:07> a rdfs:Resource .",
+            "<urn:example:08> a rdfs:Resource ; rdfs:label \"08\" .",
```
Comment (afs) [inline jena-extras/jena-serviceenhancer/src/test/java/org/apache/jena/sparql/service/enhancer/impl/TestServiceEnhancerMisc.java:498]: FYI: use single quotes to neaten up -`'08'`.

File: jena-extras/jena-serviceenhancer/src/test/java/org/apache/jena/sparql/service/enhancer/impl/TestServiceEnhancerMisc.java [hunk 3]
```diff
@@ -462,4 +471,55 @@ public void testNormalization01() {
         int actualRowCount = AbstractTestServiceEnhancerResultSetLimits.testWithCleanCaches(dataset, queryStr, 1000);
         Assert.assertEquals(4, actualRowCount);
     }
+
+    /**
+     * Test for <a href="https://github.com/apache/jena/issues/1688">JENA-1688</a>.
```
Comment (afs) [inline jena-extras/jena-serviceenhancer/src/test/java/org/apache/jena/sparql/service/enhancer/impl/TestServiceEnhancerMisc.java:476]: JENA-1688 is a JIRA from 2019!
Try: "apache/jena/issues/1688"

File: jena-extras/jena-serviceenhancer/src/test/java/org/apache/jena/sparql/service/enhancer/impl/TestServiceEnhancerMisc.java [hunk 4]
```diff
@@ -38,6 +46,7 @@
 import org.apache.jena.sparql.engine.binding.BindingFactory;
 import org.apache.jena.sparql.service.enhancer.algebra.TransformSE_JoinStrategy;
 import org.apache.jena.sparql.service.enhancer.init.ServiceEnhancerConstants;
+import org.apache.jena.sparql.service.enhancer.init.ServiceEnhancerInit;
```
Comment (afs) [inline jena-extras/jena-serviceenhancer/src/test/java/org/apache/jena/sparql/service/enhancer/impl/TestServiceEnhancerMisc.java:49]: Unused.

File: jena-extras/jena-serviceenhancer/src/test/java/org/apache/jena/sparql/service/enhancer/impl/TestServiceEnhancerMisc.java (hunk 1 above)
Comment (Aklakan) [reply jena-extras/jena-serviceenhancer/src/test/java/org/apache/jena/sparql/service/enhancer/impl/TestServiceEnhancerMisc.java:487]: Isn't it the case that on Windows or Mac a plain "\n" could lead to incorrect formatting when `System.out.println`-ing?
If you prefer "\n" then I am also fine with it.

File: jena-extras/jena-serviceenhancer/src/test/java/org/apache/jena/sparql/service/enhancer/impl/TestServiceEnhancerMisc.java (hunk 3 above)
Comment (Aklakan) [reply jena-extras/jena-serviceenhancer/src/test/java/org/apache/jena/sparql/service/enhancer/impl/TestServiceEnhancerMisc.java]: Right - updated as suggested :)

**Comment by Aklakan** [comment]
Overall this PR should be complete and  but I'd like @LorenzBuehmann to give this PR a final test himself tomorrow.

**Comment by LorenzBuehmann** [comment]
I can confirm that the issue I spotted yesterday has been resolved when using the PR code. Thanks.

File: jena-extras/jena-serviceenhancer/src/test/java/org/apache/jena/sparql/service/enhancer/impl/TestServiceEnhancerMisc.java [hunk 5]
```diff
@@ -462,4 +470,55 @@ public void testNormalization01() {
...
+
+        String queryStr = String.join(StandardSystemProperty.LINE_SEPARATOR.value(),
+            "PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>",
+            "SELECT * {",
+            "  { SELECT * { ?s a rdfs:Resource } ORDER BY ?s }",
+            "   SERVICE <loop:cache:bulk+5> { ?s rdfs:label ?l }",
+            "}");
+
+        Dataset ds = DatasetFactory.create();
+        RDFDataMgr.read(ds, new StringReader(dataStr), null, Lang.TURTLE);
```
Comment (afs) [inline jena-extras/jena-serviceenhancer/src/test/java/org/apache/jena/sparql/service/enhancer/impl/TestServiceEnhancerMisc.java:508]: FYI:
`RDFParser.fromString(dataStr).lang(Lang.TURTLE).toDataset();`

**Comment by afs** [comment]
@LorenzBuehmann - thanks for checking - it's "draft" though.

If in the next 2 hours that changes I (as release manager) will consider it for 4.7.0. The release testing has already been done, bots have already run on different OS etc  - it must be clean.

File: jena-extras/jena-serviceenhancer/src/main/java/org/apache/jena/sparql/service/enhancer/impl/util/VarScopeUtils.java [hunk 6]
```diff
@@ -37,29 +37,6 @@
  */
 public class VarScopeUtils {
 
-    public static Map<Var, Var> reverseVarRenameMap(Collection<Var> vars) {
```
Comment (Aklakan) [inline jena-extras/jena-serviceenhancer/src/main/java/org/apache/jena/sparql/service/enhancer/impl/util/VarScopeUtils.java:40]: Moved these block of methods to the end of the class - probably they can be eventually removed.

File: jena-extras/jena-serviceenhancer/src/main/java/org/apache/jena/sparql/service/enhancer/impl/RequestExecutor.java [hunk 7]
```diff
@@ -109,60 +109,60 @@ protected Binding moveToNext() {
         // Peek the next binding on the active iterator and verify that it maps to the current
         // partition key
         while (true) {
-          if (activeIter.hasNext()) {
```
Comment (Aklakan) [inline jena-extras/jena-serviceenhancer/src/main/java/org/apache/jena/sparql/service/enhancer/impl/RequestExecutor.java:112]: Fix of indentation - changed 2 spaces to 4.

File: jena-extras/jena-serviceenhancer/src/main/java/org/apache/jena/sparql/service/enhancer/impl/OpServiceInfo.java [hunk 8]
```diff
@@ -93,7 +93,7 @@ public OpServiceInfo(OpService opService) {
 
         // Handling of a null supOp - can that happen?
         Set<Var> visibleSubOpVars = OpVars.visibleVars(baseSubOp);
-        this.visibleSubOpVarsScopedToNorm = VarScopeUtils.normalizeVarScopesGlobal(visibleSubOpVars);
```
Comment (Aklakan) [inline jena-extras/jena-serviceenhancer/src/main/java/org/apache/jena/sparql/service/enhancer/impl/OpServiceInfo.java:96]: This one-liner fixes a scoping issue @LorenzBuehmann found just after he reported that this PR works while trying variants of the query that led to this PR. Instead of cut-off results it may lead to missing columns.
