### PR TITLE
GH-1419: fix DatasetGraphMap#clear 

### LINKED ISSUE #1419: method DatasetGraphMap#clear does not work correctly
### Version

4.6.0-SNAPSHOT

### What happened?

the method `org.apache.jena.sparql.core.DatasetGraphMap#clear` works incorrectly : it clears data, but leaves graph-links from internal map untouched

### Relevant output and stacktrace

_No response_

### Are you interested in making a pull request?

Yes

### PR DESCRIPTION
**Pull request by sszuev**
GitHub issue resolved #1419 

Pull request Description:

- fix `DatasetGraphMap#clear`
- fix `DatasetGraphSimpleMem` (from tests): methods clear, def-graph#find
- add tests

----

 - [x] Tests are included.
 - [ ] Documentation change and updates are provided for the [Apache Jena website](https://github.com/apache/jena-site/)
 - [x] Commits have been squashed to remove intermediate development commit messages.
 - [x] Key commit messages start with the issue number (GH-xxxx or JENA-xxxx)

By submitting this pull request, I acknowledge that I am making a contribution to the Apache Software Foundation under the terms and conditions of the [Contributor's Agreement](https://www.apache.org/licenses/contributor-agreements.html).

----

See the [Apache Jena "Contributing" guide](https://github.com/apache/jena/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Review by kinow — APPROVED** [review]

File: jena-arq/src/test/java/org/apache/jena/sparql/core/AbstractDatasetGraphTests.java [hunk 1]
```diff
@@ -328,6 +328,26 @@
         assertFalse(dsg.containsGraph(gn)) ;
     }
 
+    @Test public void clear_02() {
+        DatasetGraph dsg = emptyDataset();
+        dsg.add(new Quad(NodeFactory.createURI("g1"),
```
Comment (afs) [inline jena-arq/src/test/java/org/apache/jena/sparql/core/AbstractDatasetGraphTests.java:333]: FYI: no need to change anything:

For writing test data, you can use "SSE.parse...."

```
dsg.add(SSE.parseQuad("(<g1> <a1> <b1> <c1>)"));
```

The default graph is "_":

```
dsg.add(SSE.parseQuad("(_ <a0> <b0> <c0>)"));
```

File: jena-arq/src/test/java/org/apache/jena/sparql/core/TestTestDatasetGraphMap.java [hunk 2]
```diff
@@ -0,0 +1,9 @@
+package org.apache.jena.sparql.core;
+
+public class TestTestDatasetGraphMap extends AbstractDatasetGraphTests {
```
Comment (afs) [inline jena-arq/src/test/java/org/apache/jena/sparql/core/TestTestDatasetGraphMap.java:3]: "TestTest" -> "Test".

This also needs adding to `TS_Core` which it might a well go second in the list.

**Review by afs — CHANGES_REQUESTED** [review]
One change requested.

File: jena-arq/src/test/java/org/apache/jena/sparql/core/TestTestDatasetGraphMap.java (hunk 2 above)
Comment (sszuev) [reply jena-arq/src/test/java/org/apache/jena/sparql/core/TestTestDatasetGraphMap.java]: Thanks for review, fixed.

**Review by afs — APPROVED** [review]
Thanks!
