### PR TITLE
GH-3253: Apply transforms to present Elements of ExprFunctionOp instances.

### LINKED ISSUE #3253: ExprFunctionOp: Inconsistent Element and Op after transforms
### Version

jena-5.5.0-SNAPSHOT

### What happened?

Element and Op of `E_Exists` and `E_NotExists` become inconsistent after transform because Element is never updated. A syntax transform that renames variables in the Element thus has no effect.

The original code of these classes looks as follows:

```java
public Expr copySubstitute(Binding binding)
{
    Op op2 = Substitute.substitute(getGraphPattern(), binding) ;
    return new E_NotExists(getElement(), op2) ; // !!! Element unchanged.
}
 
@Override
public Expr applyNodeTransform(NodeTransform nodeTransform)
{
    Op op2 = NodeTransformLib.transform(nodeTransform, getGraphPattern()) ;
    return new E_NotExists(getElement(), op2) ; /// Element unchanged.
}
```

### Relevant output and stacktrace

```shell

```

### Are you interested in making a pull request?

Yes

### PR DESCRIPTION
**Pull request by Aklakan**
GitHub issue resolved #3253.
Pull request Description: Transforms now also affect Elements of ExprFunctionOp instances.

----

 - [x] Tests are included.
 - [x] Commits have been squashed to remove intermediate development commit messages.
 - [x] Key commit messages start with the issue number (GH-xxxx)

By submitting this pull request, I acknowledge that I am making a contribution to the Apache Software Foundation under the terms and conditions of the [Contributor's Agreement](https://www.apache.org/licenses/contributor-agreements.html).

----

See the [Apache Jena "Contributing" guide](https://github.com/apache/jena/blob/main/CONTRIBUTING.md).

### CODE REVIEW

File: jena-arq/src/main/java/org/apache/jena/sparql/expr/ExprFunctionOp.java [hunk 1]
```diff
@@ -53,11 +68,46 @@ public Expr getArg(int i) {
...
+        }
+        return element;
+    }
 
     @Override
     public int numArgs() { return 0; }
 
+    @Override
+    public Expr copySubstitute(Binding binding) {
+        Op op2 = Substitute.substitute(getGraphPattern(), binding) ;
```
Comment (Aklakan) [inline jena-arq/src/main/java/org/apache/jena/sparql/expr/ExprFunctionOp.java:83]: Could copySubstitute in principle delegate to applyNodeTransform with a NodeTransform based on the binding? Or are there subtle semantic difference?

File: jena-arq/src/main/java/org/apache/jena/sparql/syntax/syntaxtransform/ElementTransformSubst.java [hunk 2]
```diff
@@ -144,7 +147,10 @@ public ElementSubQuery transform(ElementSubQuery subQuery, Query newQuery) {
     public ElementData transform(ElementData data) {
         // Check for var-var. If none, no work to do.
         List<Var> vars = data.getVars();
-        boolean workToDo = vars.stream().anyMatch(v->mapping.containsKey(v));
+        boolean workToDo = vars.stream().anyMatch(v-> {
+            Node n = nodeTransform.apply(v);
+            return n != null && !v.equals(n);
+        });
```
Comment (Aklakan) [inline jena-arq/src/main/java/org/apache/jena/sparql/syntax/syntaxtransform/ElementTransformSubst.java:153]: This intent of this change is to remove the need for the explicit Map next to the NodeTransform.

File: jena-arq/src/main/java/org/apache/jena/sparql/expr/ExprFunctionOp.java (hunk 1 above)
Comment (afs) [reply jena-arq/src/main/java/org/apache/jena/sparql/expr/ExprFunctionOp.java:83]: `applyNodeTransform` works on expressions.
`Substitute.substitute(getGraphPattern(), ...)` works on `Op`s.

Until (NOT)EXISTS came along, graph patterns and expressions were quite separate and the code reflects that. But EXISTS moves between these two worlds. 

`Substitute` is likely going to be somewhat revised by the work in RDF & SPARQL Working Group on EXISTS. But there is no point revising until a degree of stability (see also `LATERAL`).

File: jena-arq/src/test/java/org/apache/jena/sparql/expr/TestExprFunctionOp_NodeTransform.java [hunk 3]
```diff
@@ -0,0 +1,81 @@
...
+import org.apache.jena.sparql.algebra.walker.Walker;
+import org.apache.jena.sparql.core.Var;
+import org.apache.jena.sparql.graph.NodeTransform;
+import org.apache.jena.sparql.graph.NodeTransformLib;
+import org.apache.jena.sparql.syntax.Element;
+import org.apache.jena.sparql.util.ExprUtils;
+import org.junit.Assert;
+import org.junit.Test;
+
+public class TestExprFunctionOp_NodeTransform {
```
Comment (afs) [inline jena-arq/src/test/java/org/apache/jena/sparql/expr/TestExprFunctionOp_NodeTransform.java:34]: Needs to go into `TS_Expr`.

File: jena-arq/src/test/java/org/apache/jena/sparql/expr/TestExprFunctionOp_ExprTransform.java [hunk 4]
```diff
@@ -0,0 +1,67 @@
...
+
+import static org.junit.Assert.assertEquals;
+
+import org.apache.jena.sparql.algebra.walker.Walker;
+import org.apache.jena.sparql.expr.TestExprFunctionOp_NodeTransform.ExprFunctionOpValidator;
+import org.apache.jena.sparql.util.ExprUtils;
+import org.junit.Assert;
+import org.junit.Test;
+
+public class TestExprFunctionOp_ExprTransform {
```
Comment (afs) [inline jena-arq/src/test/java/org/apache/jena/sparql/expr/TestExprFunctionOp_ExprTransform.java:29]: Needs to go into `TS_Expr`.

**Review by afs — CHANGES_REQUESTED** [review]

File: jena-arq/src/test/java/org/apache/jena/sparql/expr/TestExprFunctionOp_NodeTransform.java (hunk 3 above)
Comment (Aklakan) [reply jena-arq/src/test/java/org/apache/jena/sparql/expr/TestExprFunctionOp_NodeTransform.java:34]: done.

File: jena-arq/src/test/java/org/apache/jena/sparql/expr/TestExprFunctionOp_ExprTransform.java (hunk 4 above)
Comment (Aklakan) [reply jena-arq/src/test/java/org/apache/jena/sparql/expr/TestExprFunctionOp_ExprTransform.java:29]: done.

**Review by afs — APPROVED** [review]
