### PR TITLE
GH-3507: RDFS testing/wrapping framework.

### LINKED ISSUE #3507: RDFS Issues
### Version

5.6.0-SNAPSHOT

### What happened?

Having recently touched `jena-geosparql`, which uses some RDFS inferencing, brought me back to some issues:

* MatchRDFS can produce literals in subject position: `(X p "lit") (p range T) -> ("lit" a T)`.
* Many duplicate inferences even on small result sets. Perhaps introduce windowed deduplication?
* Inconsistent inferences depending how `find()` is invoked when there are sub-properties of `rdf:type`. The following examples fails for example for patterns: `:fido ?p ?o`, `?s a ?o`. I'll open a PR with a test case for all failing patterns.

```turtle
# Schema
:directType        rdfs:subPropertyOf rdf:type .

# Data
:fido :directType :Dog .
```

### Relevant output and stacktrace

```shell

```

### Are you interested in making a pull request?

None

### PR DESCRIPTION
**Pull request by Aklakan**
GitHub issue resolved #3507

Pull request Description: This is mainly infrastructure work to further assess RDFS reasoning - and any future changes to it.

* Fixed literals-in-subject inferences due to range declarations (easy fix). Added `MapperX.isLiteral` to allow for testing on `X` possibly bypassing Node-materialization.

* Fixed bug in `IteratorConcat` which would raise `IndexOutOfBoundsException` if `close()` was called without `hasNext`.

* Added testing framework that compares all combinations of invoking find(). (I hope I didn't overlook an existing system for that). Added `commons-math4` as a test-scoped dependency for the `Combinations` class.

* There is a disabled test in `AbstractTestRDFS_Extra` which fails. It uses `:directType rdfs:subPropertyOf rdf:type`. How to solve this is a separate issue - I don't think it's straight forward, so the contribution here is the test case that reveals it.

* Added infrastructure to ease wrapping `Match` implementations. Factored out `DatasetGraphWithGraphTransform` base class from `DatasetGraphRDFS` that can transform any Graph with a Match. There is a TDB2 test case that performs a simple RDFS inference on the NodeId level. The schema must be loaded into the graph though for the NodeIds to be present.

* ~~Added initial benchmark class for the RDFS reasoner.~~ [update] Removed the benchmark due to lack of scope. Can be added with a later PR to benchmark impact of specific changes.

* Added `Iter.distinctCached` in preparation to filter out some duplicates of MatchRDFS. However, this PR does not change any existing behavior. The goal is to extend AssemblerRDFS with an option for distinct/reduced behavior.

----

 - [x] Tests are included.
 - ~[ ] Documentation change and updates are provided for the [Apache Jena website](https://github.com/apache/jena-site/)~
 - [x] Commits have been squashed to remove intermediate development commit messages.
 - [x] Key commit messages start with the issue number (GH-xxxx)

By submitting this pull request, I acknowledge that I am making a contribution to the Apache Software Foundation under the terms and conditions of the [Contributor's Agreement](https://www.apache.org/licenses/contributor-agreements.html).

----

See the [Apache Jena "Contributing" guide](https://github.com/apache/jena/blob/main/CONTRIBUTING.md).

### CODE REVIEW

File: jena-arq/src/test/java/org/apache/jena/rdfs/AbstractTestRDFS_Extra.java [hunk 1]
```diff
@@ -0,0 +1,130 @@
...
+        """;
+
+        String dataStr = """
+            PREFIX :     <http://ex.org/>
+
+            :fido :directType :Dog .
+        """;
+
+        return prepareRdfsFindTests(schemaStr, dataStr).build();
+     }
```
Comment (Aklakan) [inline jena-arq/src/test/java/org/apache/jena/rdfs/AbstractTestRDFS_Extra.java]: This produces the failing test cases.

**Comment by Aklakan** [comment]
I added a test case that uses the infrastructure to perform a simple RDFS inference on the NodeId level. It's limited because it requires the ontology and the built-in properties to be present in the graph. Rdfs and owl terms would have to be pre-populated in the NodeTable. At least things can now be wired up in the way that seemed to be the intended once by having the generic X, and one can play around with it.


The relevant snippet is this:

```java
// Add wrapping on NodeId level.
Dataset baseDsg = TDB2Factory.createDataset().asDatasetGraph();
MapperX<NodeId, Tuple3<NodeId>> mapper = MapperXTDB.create(baseDsg);
ConfigRDFS<NodeId> configRDFS = RDFSFactory.setupRDFS(schema, mapper);

DatasetGraph rdfsDsg = new DatasetGraphWithGraphTransform(baseDsg,
    g -> GraphMatch.adapt(g, new MatchRDFSWrapper<>(configRDFS, MatchTDB.wrap(g))));
```
Note, that this only demonstrates a working wiring with the NodeId realm - it does not leverage QueryEngineTDB to run filters and aggregates on the NodeID level - that tighter integration would be future work.

File: jena-arq/src/main/java/org/apache/jena/rdfs/engine/ApplyRDFS.java [hunk 2]
```diff
@@ -129,10 +129,12 @@ final private void range(X s, X p, X o, Output<X> out) {
                 return;
         }
         Set<X> x = setup.getRange(p);
-        x.forEach(c -> {
-            derive(o, rdfType, c, out);
-            subClass(o, rdfType, c, out);
-        });
+        if (!mapper.isLiteral(o)) {
```
Comment (Aklakan) [inline jena-arq/src/main/java/org/apache/jena/rdfs/engine/ApplyRDFS.java:132]: The question is how to minimize materialization in this check. One can check for whether a NodeId is an inlined value and return early. But not sure if from the NodeId alone it can be decided whether it's a literal or not.

**Comment by afs** [comment]
Please could you bring this up-to-date with 6.0.0? Thanks.

**Comment by afs** [comment]
> Fixed literals-in-subject inferences due to range declarations (easy fix)

To help me, where exactly is this?

**Comment by afs** [comment]
>  It uses :directType rdfs:subPropertyOf rdf:type.

In the schema presumably.

Subproperties of the RDFS vocabulary are not intended to be supported by this data-centric RDFS system (rdfs:subClassOf, rdfs:domain, rdfs:range).

"messing around with the scaffolding"

It ought to raise an error in all four cases.
