### PR TITLE
GH-2219 : Check for existence of Z axis and measure to avoid exception when neither is available

### LINKED ISSUE #2219: GeoSPARQL -  geof:sfIntersects function issue when left-hand side geometry is rectangle shape
### Version

4.10.0 and 5.0.0-SNAPSHOT

### What happened?

Calling the GeoSPARQL function `geof:sfIntersects` with e.g. `FILTER(geof:sfIntersects(?g1, ?g2))` can lead to an exception when the first geometry `g1`is an rectangle. See the following code to reproduce:

``` java
package org.apache.jena.geosparql;

import org.apache.jena.geosparql.implementation.GeometryWrapper;
import org.apache.jena.geosparql.implementation.vocabulary.GeoSPARQL_URI;
import org.apache.jena.graph.Node;
import org.apache.jena.riot.system.PrefixMap;
import org.apache.jena.riot.system.PrefixMapFactory;
import org.apache.jena.sparql.util.NodeFactoryExtra;

public class GeometryIntersectionBug {

    public static void main(String[] args) throws Exception {
        PrefixMap pm = PrefixMapFactory.create(GeoSPARQL_URI.getPrefixes());

        // a hexagon
        String polygonLitStr = "\"POLYGON ((10.0656923 55.3948787, 9.3745308 53.9755137, 11.2451705 53.0320397, 13.8395286 53.4872452, 14.6402066 54.9021819, 12.739823 55.8673267, 10.0656923 55.3948787))\"^^geo:wktLiteral";
        Node polygonNode = NodeFactoryExtra.parseNode(polygonLitStr, pm);
        GeometryWrapper polygonGeom = GeometryWrapper.extract(polygonNode);

        // a rectangle
        String rectangleLitStr = "\"POLYGON((6.2520337 47.7361897, 6.2520337 53.7746148, 14.0584217 53.7746148, 14.0584217 47.7361897, 6.2520337 47.7361897))\"^^geo:wktLiteral";
        Node rectangleNode = NodeFactoryExtra.parseNode(rectangleLitStr, pm);
        GeometryWrapper rectangleGeom = GeometryWrapper.extract(rectangleNode);

        // check if both geometries intersect
        boolean intersects1  = polygonGeom.intersects(rectangleGeom); // works

        boolean intersects2 = rectangleGeom.intersects(polygonGeom); // error

    }
}
```
It happens because the underlying JTS API does use an optimized algorithm for rectangles to terminate as early as possible. During this algorithm some new `Coordinate` objects will be created which make use of some Jena specific implementation which assumes not only XY geometries but also the Z axis. This results in an exception.

### Relevant output and stacktrace

```shell
Exception in thread "main" java.lang.IllegalArgumentException: CoordinateXY dimension 2 does not support z-ordinate
	at org.locationtech.jts.geom.CoordinateXY.setZ(CoordinateXY.java:99)
	at org.apache.jena.geosparql.implementation.jts.CustomCoordinateSequence.getCoordinate(CustomCoordinateSequence.java:397)
	at org.locationtech.jts.operation.predicate.RectangleIntersectsSegmentVisitor.checkIntersectionWithSegments(RectangleIntersects.java:327)
	at org.locationtech.jts.operation.predicate.RectangleIntersectsSegmentVisitor.checkIntersectionWithLineStrings(RectangleIntersects.java:315)
	at org.locationtech.jts.operation.predicate.RectangleIntersectsSegmentVisitor.visit(RectangleIntersects.java:308)
	at org.locationtech.jts.geom.util.ShortCircuitedGeometryVisitor.applyTo(ShortCircuitedGeometryVisitor.java:35)
	at org.locationtech.jts.operation.predicate.RectangleIntersects.intersects(RectangleIntersects.java:110)
	at org.locationtech.jts.operation.predicate.RectangleIntersects.intersects(RectangleIntersects.java:58)
	at org.locationtech.jts.geom.prep.PreparedPolygon.intersects(PreparedPolygon.java:84)
	at org.apache.jena.geosparql.implementation.GeometryWrapper.intersects(GeometryWrapper.java:882)
	at org.apache.jena.geosparql.GeometryIntersectionBug.main(GeometryIntersectionBug.java:29)
```

### Are you interested in making a pull request?

Maybe

### PR DESCRIPTION
**Pull request by LorenzBuehmann**
GitHub issue resolved #2219

Pull request Description:
Does fix an issue when Z axis isn't available.

----

 - [ ] Tests are included.
 - [ ] Documentation change and updates are provided for the [Apache Jena website](https://github.com/apache/jena-site/)
 - [x] Commits have been squashed to remove intermediate development commit messages.
 - [x] Key commit messages start with the issue number (GH-xxxx, or if in JIRA, JENA-xxxx)

By submitting this pull request, I acknowledge that I am making a contribution to the Apache Software Foundation under the terms and conditions of the [Contributor's Agreement](https://www.apache.org/licenses/contributor-agreements.html).

----

See the [Apache Jena "Contributing" guide](https://github.com/apache/jena/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Comment by afs** [comment]
Could you add a test for this please?

One place might be `WKTDatatypeTest` (and `GMLDatatypeTest`) but that may not be a good fit.

If nothing else, a new test class in `org.apache.jena.geosparql.implementation.jts`.

**Comment by LorenzBuehmann** [comment]
I added a test class for the `CustomCoordinateSequence` class on the JTS level. The test does check the creation of a `Coordinate` for the different combinations of the spatial and measure dimension.

File: jena-geosparql/src/test/java/org/apache/jena/geosparql/implementation/jts/CustomCoordinateSequenceTest.java [hunk 1]
```diff
@@ -0,0 +1,85 @@
+package org.apache.jena.geosparql.implementation.jts;
```
Comment (afs) [inline jena-geosparql/src/test/java/org/apache/jena/geosparql/implementation/jts/CustomCoordinateSequenceTest.java:1]: No license header. Please could you add one - the text from one of the adjacent files.

(It is better if the contributor adds the license rather than someone else add it. PS The build checks!)

File: jena-geosparql/src/test/java/org/apache/jena/geosparql/implementation/jts/CustomCoordinateSequenceTest.java [hunk 2]
```diff
@@ -0,0 +1,85 @@
...
+        int index = 1;
+
+        sequence.getCoordinate(index, coord);
+
+        assertEquals(2.0, coord.getX(), 0.001);
+        assertEquals(2.0, coord.getY(), 0.001);
+        assertTrue(Double.isNaN(coord.getZ()));
+        assertEquals(2.0, coord.getM(), 0.001);
+    }
+}
```
Comment (afs) [inline jena-geosparql/src/test/java/org/apache/jena/geosparql/implementation/jts/CustomCoordinateSequenceTest.java:85]:
```suggestion
}

```

**Review by afs — CHANGES_REQUESTED** [review]

**Comment by afs** [comment]
Other than the license (and a minor issue format issue), this PR looks and builds properly.

**Review by afs — APPROVED** [review]
Thanks!
